use std::cmp::Reverse;
use std::collections::{BTreeMap, BTreeSet, HashMap, VecDeque};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use clap::Args;
use serde::Serialize;
use tempfile::NamedTempFile;

use super::{Diagnostic, Evidence, build_evidence, in_scope, is_test_path, line_column};

const TEMPLATE: &str = include_str!("../../templates/call-graph.html");
const DATA_PLACEHOLDER: &str = "__JT_GRAPH_DATA__";
const OWNERSHIP_MARKER: &str = "<!-- generated by jt call-graph -->";
const MAX_EMBEDDED_NODES: usize = 20_000;
const MAX_EMBEDDED_EDGES: usize = 80_000;

#[derive(Debug, Args)]
pub struct CallGraphArgs {
    /// Project root or initial graph scope; default: current directory
    #[arg(value_name = "PATH", default_value = ".")]
    path: PathBuf,
    /// Output HTML path, relative to project root unless absolute
    #[arg(short, long, default_value = ".nlab/call-graph.html")]
    output: PathBuf,
    /// Initial center: exact symbol name, qualified name, ID, or path:line
    #[arg(long)]
    focus: Option<String>,
    /// Initial caller/callee traversal depth
    #[arg(long, default_value_t = 2, value_parser = clap::value_parser!(u8).range(1..=8))]
    depth: u8,
    /// Maximum nodes displayed in the initial view
    #[arg(long, default_value_t = 400, value_parser = clap::value_parser!(u16).range(1..=2000))]
    max_nodes: u16,
    /// Open the generated HTML in the system browser
    #[arg(long)]
    open: bool,
    /// Replace an existing HTML file not generated by jt
    #[arg(long)]
    force: bool,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct GraphNode {
    id: String,
    name: String,
    qualified_name: String,
    kind: String,
    language: String,
    path: String,
    line: usize,
    column: usize,
    degree: usize,
    in_scope: bool,
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd, Serialize)]
struct CallSite {
    path: String,
    line: Option<usize>,
    column: Option<usize>,
}

#[derive(Clone, Debug, Serialize)]
struct GraphLink {
    source: String,
    target: String,
    kind: String,
    confidence: String,
    count: usize,
    sites: Vec<CallSite>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct GraphData {
    version: u8,
    root: String,
    scope: String,
    scan_roots: Vec<String>,
    exclude: Vec<String>,
    focus: Option<String>,
    depth: u8,
    total_nodes: usize,
    total_edges: usize,
    truncated: bool,
    initial_nodes: Vec<String>,
    nodes: Vec<GraphNode>,
    edges: Vec<GraphLink>,
    diagnostics: Vec<Diagnostic>,
}

#[derive(Default)]
struct LinkAccumulator {
    sites: BTreeSet<CallSite>,
}

pub(super) fn run(args: CallGraphArgs) -> u8 {
    match generate(&args) {
        Ok((path, nodes, edges)) => {
            println!("Call graph: {}", path.display());
            println!("{nodes} nodes, {edges} directed edges");
            if args.open {
                if let Err(error) = open_html(&path) {
                    eprintln!("error: {error}");
                    return 1;
                }
            }
            0
        }
        Err(error) => {
            eprintln!("error: {error}");
            1
        }
    }
}

fn generate(args: &CallGraphArgs) -> Result<(PathBuf, usize, usize), String> {
    let evidence = build_evidence(&args.path)?;
    let project_root = evidence.project.root.clone();
    let mut data = build_graph(evidence, args)?;
    let node_count = data.nodes.len();
    let edge_count = data.edges.len();
    data.diagnostics.sort_by(|left, right| {
        (&left.path, left.line, &left.code, &left.message).cmp(&(
            &right.path,
            right.line,
            &right.code,
            &right.message,
        ))
    });
    let json = serde_json::to_string(&data)
        .map_err(|error| format!("cannot serialize call graph: {error}"))?;
    let json = escape_inline_json(&json);
    if TEMPLATE.matches(DATA_PLACEHOLDER).count() != 1 {
        return Err("call graph HTML template has an invalid data placeholder".to_owned());
    }
    let html = TEMPLATE.replace(DATA_PLACEHOLDER, &json);
    let output = if args.output.is_absolute() {
        args.output.clone()
    } else {
        validate_relative_output(&project_root, &args.output)?;
        project_root.join(&args.output)
    };
    write_html(&output, &html, args.force)?;
    Ok((output, node_count, edge_count))
}

fn validate_relative_output(root: &Path, output: &Path) -> Result<(), String> {
    if output.components().any(|component| {
        matches!(
            component,
            std::path::Component::ParentDir
                | std::path::Component::RootDir
                | std::path::Component::Prefix(_)
        )
    }) {
        return Err("relative call graph output cannot contain .. or a root prefix".to_owned());
    }
    let mut current = root.to_path_buf();
    for component in output.parent().into_iter().flat_map(Path::components) {
        let std::path::Component::Normal(component) = component else {
            continue;
        };
        current.push(component);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(format!(
                    "refusing relative output through symlink: {}",
                    current.display()
                ));
            }
            Ok(metadata) if !metadata.is_dir() => {
                return Err(format!(
                    "output parent is not a directory: {}",
                    current.display()
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => break,
            Err(error) => {
                return Err(format!("cannot inspect {}: {error}", current.display()));
            }
        }
    }
    Ok(())
}

fn build_graph(evidence: Evidence, args: &CallGraphArgs) -> Result<GraphData, String> {
    let Evidence {
        project,
        sources,
        scan,
        semantic_edges,
        ..
    } = evidence;
    let mut nodes = Vec::new();
    for candidate in &scan.candidates {
        if !sources.included_paths.contains(&candidate.path) || is_test_path(&candidate.path) {
            continue;
        }
        let (line, column) = sources
            .contents
            .get(&candidate.path)
            .map_or((candidate.line, candidate.column), |content| {
                line_column(content, candidate.start)
            });
        nodes.push(GraphNode {
            id: candidate.id.clone(),
            name: candidate.name.clone(),
            qualified_name: candidate.qualified_name.clone(),
            kind: candidate.kind.clone(),
            language: candidate.language.clone(),
            path: candidate.path.clone(),
            line,
            column,
            degree: 0,
            in_scope: in_scope(&project, &candidate.path),
        });
    }
    for module in &scan.modules {
        if !sources.included_paths.contains(&module.path) || is_test_path(&module.path) {
            continue;
        }
        nodes.push(GraphNode {
            id: format!("file::{}", module.path),
            name: Path::new(&module.path)
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or(&module.path)
                .to_owned(),
            qualified_name: module.path.clone(),
            kind: "file".to_owned(),
            language: super::language_for_path(&module.path).to_owned(),
            path: module.path.clone(),
            line: 1,
            column: 1,
            degree: 0,
            in_scope: in_scope(&project, &module.path),
        });
    }
    nodes.sort_by(|left, right| left.id.cmp(&right.id));
    nodes.dedup_by(|left, right| left.id == right.id);
    let node_ids = nodes
        .iter()
        .map(|node| node.id.clone())
        .collect::<BTreeSet<_>>();

    let mut links = BTreeMap::<(String, String, String, String), LinkAccumulator>::new();
    for node in nodes.iter().filter(|node| node.kind != "file") {
        let file = format!("file::{}", node.path);
        if !node_ids.contains(&file) {
            continue;
        }
        add_link(
            &mut links,
            &file,
            &node.id,
            "contains",
            "exact",
            CallSite {
                path: node.path.clone(),
                line: Some(node.line),
                column: Some(node.column),
            },
        );
    }
    for edge in &scan.edges {
        if !node_ids.contains(&edge.source) || !node_ids.contains(&edge.target) {
            continue;
        }
        let (line, column) = sources
            .contents
            .get(&edge.path)
            .map_or((edge.line, edge.column), |content| {
                line_column(content, edge.start)
            });
        add_link(
            &mut links,
            &edge.source,
            &edge.target,
            &edge.kind,
            &edge.confidence,
            CallSite {
                path: edge.path.clone(),
                line: Some(line),
                column: Some(column),
            },
        );
    }
    for edge in &semantic_edges {
        if !node_ids.contains(&edge.source) || !node_ids.contains(&edge.target) {
            continue;
        }
        add_link(
            &mut links,
            &edge.source,
            &edge.target,
            &edge.kind,
            &edge.confidence,
            CallSite {
                path: edge.path.clone(),
                line: edge.line,
                column: edge.column,
            },
        );
    }
    let mut edges = links
        .into_iter()
        .map(|((source, target, kind, confidence), link)| {
            let precise_paths = link
                .sites
                .iter()
                .filter(|site| site.line.is_some())
                .map(|site| site.path.clone())
                .collect::<BTreeSet<_>>();
            let sites = link
                .sites
                .into_iter()
                .filter(|site| site.line.is_some() || !precise_paths.contains(&site.path))
                .collect::<Vec<_>>();
            GraphLink {
                source,
                target,
                kind,
                confidence,
                count: sites.len(),
                sites,
            }
        })
        .collect::<Vec<_>>();
    edges.sort_by(|left, right| {
        (&left.source, &left.target, &left.kind, &left.confidence).cmp(&(
            &right.source,
            &right.target,
            &right.kind,
            &right.confidence,
        ))
    });

    let mut degree = HashMap::<String, usize>::new();
    let mut call_adjacency = HashMap::<String, BTreeSet<String>>::new();
    let mut all_adjacency = HashMap::<String, BTreeSet<String>>::new();
    for edge in &edges {
        *degree.entry(edge.source.clone()).or_default() += 1;
        *degree.entry(edge.target.clone()).or_default() += 1;
        all_adjacency
            .entry(edge.source.clone())
            .or_default()
            .insert(edge.target.clone());
        all_adjacency
            .entry(edge.target.clone())
            .or_default()
            .insert(edge.source.clone());
        if matches!(edge.kind.as_str(), "calls" | "instantiates") {
            call_adjacency
                .entry(edge.source.clone())
                .or_default()
                .insert(edge.target.clone());
            call_adjacency
                .entry(edge.target.clone())
                .or_default()
                .insert(edge.source.clone());
        }
    }
    for node in &mut nodes {
        node.degree = degree.get(&node.id).copied().unwrap_or_default();
    }

    let focus = resolve_focus(args.focus.as_deref(), &nodes)?;
    let focus_is_file = focus.as_deref().is_some_and(|focus| {
        nodes
            .iter()
            .any(|node| node.id == focus && node.kind == "file")
    });
    let distances = graph_distances(
        focus.as_deref(),
        &nodes,
        if focus_is_file {
            &all_adjacency
        } else {
            &call_adjacency
        },
        usize::from(args.depth),
    );
    let total_nodes = nodes.len();
    let total_edges = edges.len();
    if total_nodes > MAX_EMBEDDED_NODES || total_edges > MAX_EMBEDDED_EDGES {
        return Err(format!(
            "call graph has {total_nodes} nodes and {total_edges} edges; narrow .nlab/unused.config.json roots/exclude below the {MAX_EMBEDDED_NODES}-node/{MAX_EMBEDDED_EDGES}-edge safety limit"
        ));
    }
    let mut ranked = nodes.clone();
    if focus.is_some() || !project.scope.is_empty() {
        ranked.retain(|node| distances.contains_key(&node.id));
    }
    ranked.sort_by(|left, right| {
        let left_distance = distances.get(&left.id).copied().unwrap_or(usize::MAX);
        let right_distance = distances.get(&right.id).copied().unwrap_or(usize::MAX);
        (
            left_distance,
            !left.in_scope,
            left.kind == "file",
            Reverse(left.degree),
            left.path.as_str(),
            left.line,
            left.name.as_str(),
        )
            .cmp(&(
                right_distance,
                !right.in_scope,
                right.kind == "file",
                Reverse(right.degree),
                right.path.as_str(),
                right.line,
                right.name.as_str(),
            ))
    });
    let initial_nodes = select_initial_nodes(&ranked, usize::from(args.max_nodes));
    let truncated = ranked.len() > initial_nodes.len();
    nodes.sort_by(|left, right| left.id.cmp(&right.id));

    let diagnostics = sources
        .diagnostics
        .into_iter()
        .filter(|diagnostic| {
            diagnostic.path.as_deref().is_none_or(|path| {
                project
                    .config
                    .includes(&project.root, Path::new(path), false)
            })
        })
        .collect();
    Ok(GraphData {
        version: 1,
        root: project.root.to_string_lossy().into_owned(),
        scope: if project.scope.is_empty() {
            ".".to_owned()
        } else {
            project.scope
        },
        scan_roots: project
            .config
            .roots
            .iter()
            .map(|root| root.display.clone())
            .collect(),
        exclude: project.config.exclude_patterns,
        focus,
        depth: args.depth,
        total_nodes,
        total_edges,
        truncated,
        initial_nodes,
        nodes,
        edges,
        diagnostics,
    })
}

fn add_link(
    links: &mut BTreeMap<(String, String, String, String), LinkAccumulator>,
    source: &str,
    target: &str,
    kind: &str,
    confidence: &str,
    site: CallSite,
) {
    let kind = if kind == "call" { "calls" } else { kind };
    let link = links
        .entry((
            source.to_owned(),
            target.to_owned(),
            kind.to_owned(),
            confidence.to_owned(),
        ))
        .or_default();
    link.sites.insert(site);
}

fn resolve_focus(focus: Option<&str>, nodes: &[GraphNode]) -> Result<Option<String>, String> {
    let Some(query) = focus else {
        return Ok(None);
    };
    let mut matches = nodes
        .iter()
        .filter(|node| {
            node.id == query
                || node.name == query
                || node.qualified_name == query
                || format!("{}:{}", node.path, node.line) == query
        })
        .collect::<Vec<_>>();
    matches.sort_by(|left, right| {
        (&left.path, left.line, &left.id).cmp(&(&right.path, right.line, &right.id))
    });
    match matches.as_slice() {
        [] => Err(format!("call graph focus not found: {query}")),
        [node] => Ok(Some(node.id.clone())),
        _ => Err(format!(
            "call graph focus is ambiguous: {query}; use path:line"
        )),
    }
}

fn graph_distances(
    focus: Option<&str>,
    nodes: &[GraphNode],
    adjacency: &HashMap<String, BTreeSet<String>>,
    depth: usize,
) -> HashMap<String, usize> {
    let mut distances = HashMap::new();
    let mut queue = VecDeque::new();
    if let Some(focus) = focus {
        distances.insert(focus.to_owned(), 0);
        queue.push_back(focus.to_owned());
    } else {
        for node in nodes.iter().filter(|node| node.in_scope) {
            distances.insert(node.id.clone(), 0);
            queue.push_back(node.id.clone());
        }
    }
    while let Some(node) = queue.pop_front() {
        let distance = distances[&node];
        if distance >= depth {
            continue;
        }
        for neighbor in adjacency.get(&node).into_iter().flatten() {
            if distances.contains_key(neighbor) {
                continue;
            }
            distances.insert(neighbor.clone(), distance + 1);
            queue.push_back(neighbor.clone());
        }
    }
    distances
}

fn select_initial_nodes(nodes: &[GraphNode], maximum: usize) -> Vec<String> {
    if nodes.len() <= maximum {
        return nodes.iter().map(|node| node.id.clone()).collect();
    }
    let file_limit = (maximum / 4).max(1);
    let method_limit = (maximum / 5).max(1);
    let symbol_limit = maximum.saturating_sub(file_limit + method_limit);
    let mut selected = BTreeSet::new();
    for node in nodes
        .iter()
        .filter(|node| {
            !matches!(
                node.kind.as_str(),
                "file" | "method" | "class" | "constructor"
            )
        })
        .take(symbol_limit)
    {
        selected.insert(node.id.clone());
    }
    for node in nodes
        .iter()
        .filter(|node| matches!(node.kind.as_str(), "method" | "class" | "constructor"))
        .take(method_limit)
    {
        selected.insert(node.id.clone());
    }
    for node in nodes
        .iter()
        .filter(|node| node.kind == "file")
        .take(file_limit)
    {
        selected.insert(node.id.clone());
    }
    for node in nodes {
        if selected.len() >= maximum {
            break;
        }
        selected.insert(node.id.clone());
    }
    nodes
        .iter()
        .filter(|node| selected.contains(&node.id))
        .map(|node| node.id.clone())
        .collect()
}

fn escape_inline_json(json: &str) -> String {
    json.replace('&', "\\u0026")
        .replace('<', "\\u003c")
        .replace('>', "\\u003e")
        .replace('\u{2028}', "\\u2028")
        .replace('\u{2029}', "\\u2029")
}

fn write_html(path: &Path, html: &str, force: bool) -> Result<(), String> {
    if let Ok(metadata) = fs::symlink_metadata(path) {
        if metadata.file_type().is_symlink() {
            return Err(format!("refusing to replace symlink: {}", path.display()));
        }
        if !metadata.is_file() {
            return Err(format!("output is not a regular file: {}", path.display()));
        }
        if !force {
            let current = fs::read_to_string(path)
                .map_err(|error| format!("cannot read {}: {error}", path.display()))?;
            if !current.contains(OWNERSHIP_MARKER) {
                return Err(format!(
                    "refusing to replace unowned HTML: {} (use --force)",
                    path.display()
                ));
            }
        }
    }
    let parent = path
        .parent()
        .ok_or_else(|| format!("output has no parent: {}", path.display()))?;
    fs::create_dir_all(parent)
        .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
    let mut temporary = NamedTempFile::new_in(parent)
        .map_err(|error| format!("cannot create call graph temporary file: {error}"))?;
    temporary
        .write_all(html.as_bytes())
        .map_err(|error| format!("cannot write call graph: {error}"))?;
    temporary
        .as_file()
        .sync_all()
        .map_err(|error| format!("cannot sync call graph: {error}"))?;
    temporary
        .persist(path)
        .map_err(|error| format!("cannot replace {}: {}", path.display(), error.error))?;
    Ok(())
}

fn open_html(path: &Path) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    let mut command = Command::new("open");
    #[cfg(target_os = "linux")]
    let mut command = Command::new("xdg-open");
    #[cfg(target_os = "windows")]
    let mut command = {
        let mut command = Command::new("cmd");
        command.args(["/C", "start", ""]);
        command
    };
    #[cfg(not(any(target_os = "macos", target_os = "linux", target_os = "windows")))]
    return Err("--open is unsupported on this platform".to_owned());

    let status = command
        .arg(path)
        .status()
        .map_err(|error| format!("cannot open {}: {error}", path.display()))?;
    if !status.success() {
        return Err(format!("browser opener exited with {status}"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inline_json_escapes_script_breakout_characters() {
        let escaped = escape_inline_json("{\"name\":\"</script>&\u{2028}\"}");
        assert!(!escaped.contains('<'));
        assert!(!escaped.contains('&'));
        assert!(escaped.contains("\\u003c/script\\u003e"));
    }

    #[test]
    fn initial_selection_keeps_file_nodes() {
        let nodes = (0..12)
            .map(|index| GraphNode {
                id: format!("node-{index}"),
                name: format!("node-{index}"),
                qualified_name: format!("node-{index}"),
                kind: if index < 4 { "file" } else { "function" }.to_owned(),
                language: "typescript".to_owned(),
                path: format!("src/{index}.ts"),
                line: 1,
                column: 1,
                degree: 1,
                in_scope: true,
            })
            .collect::<Vec<_>>();
        let selected = select_initial_nodes(&nodes, 8);
        assert_eq!(selected.len(), 8);
        assert!(
            selected
                .iter()
                .filter(|id| id.starts_with("node-") && id[5..].parse::<usize>().unwrap() < 4)
                .count()
                >= 2
        );
    }

    #[test]
    fn exact_and_potential_sites_stay_separate() {
        let mut links = BTreeMap::new();
        for confidence in ["exact", "potential"] {
            add_link(
                &mut links,
                "source",
                "target",
                "dynamic-import",
                confidence,
                CallSite {
                    path: "src/main.ts".to_owned(),
                    line: Some(1),
                    column: Some(1),
                },
            );
        }
        assert_eq!(links.len(), 2);
    }
}
