use std::collections::BTreeSet;
use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result, bail};
use sha2::{Digest, Sha256};

use super::model::{ContractIr, FrontendManifest};
use super::openapi::OpenApiArtifact;
use super::typescript::FrontendArtifact;

const GENERATED_HEADER: &str = "// Generated by jt nlab-api. Do not edit manually.";
const ORVAL_GENERATED_MARKER: &str = "Generated by orval";

pub struct OutputLock {
    path: PathBuf,
    _file: File,
}

pub struct WrittenArtifacts {
    pub openapi_path: PathBuf,
    pub openapi_sha256: String,
    pub api_files: Vec<String>,
    pub type_files: Vec<String>,
    pub enum_files: Vec<String>,
}

impl OutputLock {
    pub fn acquire(root: &Path) -> Result<Self> {
        fs::create_dir_all(root.join(".nlab"))
            .with_context(|| format!("create output state directory in {}", root.display()))?;
        let path = root.join(".nlab/core-generation.lock");
        let mut file = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&path)
            .with_context(|| {
                format!(
                    "core generation already running or lock unavailable: {}",
                    path.display()
                )
            })?;
        writeln!(file, "pid={}", std::process::id())?;
        Ok(Self { path, _file: file })
    }
}

impl Drop for OutputLock {
    fn drop(&mut self) {
        let _ = fs::remove_file(&self.path);
    }
}

pub fn write(
    root: &Path,
    ir: &ContractIr,
    openapi: &OpenApiArtifact,
    frontend: &FrontendArtifact,
) -> Result<WrittenArtifacts> {
    fs::create_dir_all(root)
        .with_context(|| format!("create output directory {}", root.display()))?;
    let canonical_root = root
        .canonicalize()
        .with_context(|| format!("resolve output directory {}", root.display()))?;
    let openapi_sha256 = hex_sha256(openapi.source.as_bytes());
    let manifest = FrontendManifest {
        version: 1,
        layout: None,
        app_name: ir.target.app_name.clone(),
        branch: ir.target.branch.clone(),
        commit: ir.target.commit.clone(),
        openapi_sha256: openapi_sha256.clone(),
        api_files: frontend.api_files.clone(),
        type_files: frontend.type_files.clone(),
        enum_files: frontend.enum_files.clone(),
    };
    let previous_manifest = fs::read_to_string(canonical_root.join(".nlab/frontend-manifest.json"))
        .ok()
        .and_then(|source| serde_json::from_str::<FrontendManifest>(&source).ok());
    let manifest_source = format!("{}\n", serde_json::to_string_pretty(&manifest)?);
    let ir_source = format!("{}\n", serde_json::to_string_pretty(ir)?);
    let mut sources = frontend.files.clone();
    sources.insert(
        ".nlab/openapi.pending.json".to_owned(),
        openapi.source.clone(),
    );
    sources.insert(".nlab/frontend-manifest.json".to_owned(), manifest_source);
    sources.insert(".nlab/contract-ir.json".to_owned(), ir_source);
    for relative in sources.keys() {
        let target = safe_target(&canonical_root, relative)?;
        preflight_target(relative, &target, previous_manifest.is_some())?;
    }
    preflight_stale_files(&canonical_root, previous_manifest.as_ref(), &manifest)?;
    let remove_legacy_openapi = legacy_root_openapi_is_managed(
        &canonical_root,
        &openapi_sha256,
        previous_manifest.as_ref(),
    )?;

    let stage = tempfile::Builder::new()
        .prefix(".nlab-stage-")
        .tempdir_in(&canonical_root)
        .context("create output staging directory")?;
    for (relative, source) in &sources {
        let target = stage.path().join(relative);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&target, source).with_context(|| format!("stage generated file {relative}"))?;
    }
    const MANIFEST_PATH: &str = ".nlab/frontend-manifest.json";
    for relative in sources
        .keys()
        .filter(|relative| relative.as_str() != MANIFEST_PATH)
    {
        let staged = stage.path().join(relative);
        let target = safe_target(&canonical_root, relative)?;
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::rename(&staged, &target)
            .with_context(|| format!("promote generated file {relative}"))?;
    }
    remove_stale_files(&canonical_root, previous_manifest.as_ref(), &manifest)?;
    prune_empty_directories(&canonical_root, &frontend.managed_roots)?;
    fs::rename(
        stage.path().join(MANIFEST_PATH),
        safe_target(&canonical_root, MANIFEST_PATH)?,
    )
    .context("promote frontend manifest")?;
    if remove_legacy_openapi {
        fs::remove_file(canonical_root.join("openapi.json"))
            .context("remove legacy root OpenAPI")?;
    }
    Ok(WrittenArtifacts {
        openapi_path: canonical_root.join(".nlab/openapi.pending.json"),
        openapi_sha256,
        api_files: frontend.api_files.clone(),
        type_files: frontend.type_files.clone(),
        enum_files: frontend.enum_files.clone(),
    })
}

fn legacy_root_openapi_is_managed(
    root: &Path,
    current_sha256: &str,
    previous: Option<&FrontendManifest>,
) -> Result<bool> {
    let path = root.join("openapi.json");
    let Ok(metadata) = fs::symlink_metadata(&path) else {
        return Ok(false);
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        bail!("refuse to inspect non-file or symlink: {}", path.display());
    }
    let hash = hex_sha256(&fs::read(&path)?);
    Ok(hash == current_sha256 || previous.is_some_and(|manifest| manifest.openapi_sha256 == hash))
}

fn prune_empty_directories(root: &Path, managed_roots: &[String]) -> Result<()> {
    for relative in managed_roots {
        let managed = safe_target(root, relative)?;
        let Ok(metadata) = fs::symlink_metadata(&managed) else {
            continue;
        };
        if metadata.file_type().is_symlink() || !metadata.is_dir() {
            bail!(
                "managed output root must be a real directory: {}",
                managed.display()
            );
        }
        for entry in fs::read_dir(&managed)? {
            let entry = entry?;
            if entry.file_type()?.is_dir() {
                prune_directory(&entry.path())?;
            }
        }
    }
    Ok(())
}

fn prune_directory(path: &Path) -> Result<()> {
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        if entry.file_type()?.is_dir() {
            prune_directory(&entry.path())?;
        }
    }
    if fs::read_dir(path)?.next().is_none() {
        fs::remove_dir(path)
            .with_context(|| format!("remove empty directory {}", path.display()))?;
    }
    Ok(())
}

fn remove_stale_files(
    root: &Path,
    previous: Option<&FrontendManifest>,
    current: &FrontendManifest,
) -> Result<()> {
    let Some(previous) = previous else {
        return Ok(());
    };
    let current_files = current
        .api_files
        .iter()
        .chain(&current.type_files)
        .chain(&current.enum_files)
        .cloned()
        .collect::<BTreeSet<_>>();
    for relative in previous
        .api_files
        .iter()
        .chain(&previous.type_files)
        .chain(&previous.enum_files)
        .filter(|relative| !current_files.contains(*relative))
    {
        let target = safe_target(root, relative)?;
        let Ok(source) = fs::read_to_string(&target) else {
            continue;
        };
        if !is_owned_generated_source(&source) && !is_legacy_bridge_manifest(previous) {
            bail!(
                "refuse to remove modified generated file: {}",
                target.display()
            );
        }
        fs::remove_file(&target)
            .with_context(|| format!("remove stale generated file {relative}"))?;
    }
    Ok(())
}

fn preflight_stale_files(
    root: &Path,
    previous: Option<&FrontendManifest>,
    current: &FrontendManifest,
) -> Result<()> {
    let Some(previous) = previous else {
        return Ok(());
    };
    let current_files = current
        .api_files
        .iter()
        .chain(&current.type_files)
        .chain(&current.enum_files)
        .collect::<BTreeSet<_>>();
    for relative in previous
        .api_files
        .iter()
        .chain(&previous.type_files)
        .chain(&previous.enum_files)
        .filter(|relative| !current_files.contains(relative))
    {
        let target = safe_target(root, relative)?;
        let Ok(source) = fs::read_to_string(&target) else {
            continue;
        };
        if !is_owned_generated_source(&source) && !is_legacy_bridge_manifest(previous) {
            bail!(
                "refuse to remove modified generated file: {}",
                target.display()
            );
        }
    }
    Ok(())
}

fn is_legacy_bridge_manifest(manifest: &FrontendManifest) -> bool {
    manifest.layout.as_deref() == Some("service-paths")
}

fn preflight_target(relative: &str, target: &Path, has_manifest: bool) -> Result<()> {
    let Ok(metadata) = fs::symlink_metadata(target) else {
        return Ok(());
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        bail!(
            "refuse to overwrite non-file or symlink: {}",
            target.display()
        );
    }
    if relative.ends_with(".ts") {
        let source = fs::read_to_string(target)
            .with_context(|| format!("read existing generated target {}", target.display()))?;
        if !is_owned_generated_source(&source) {
            bail!(
                "refuse to overwrite non-generated file: {}",
                target.display()
            );
        }
    } else if !has_manifest {
        bail!(
            "refuse to overwrite unmanaged nlab-api artifact: {}",
            target.display()
        );
    }
    Ok(())
}

fn is_owned_generated_source(source: &str) -> bool {
    if source.starts_with(GENERATED_HEADER) {
        return true;
    }
    let header = source.lines().take(8).collect::<Vec<_>>().join("\n");
    header.contains(ORVAL_GENERATED_MARKER) && header.contains("Do not edit manually")
}

fn safe_target(root: &Path, relative: &str) -> Result<PathBuf> {
    let relative = Path::new(relative);
    if relative.is_absolute()
        || relative
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
    {
        bail!("unsafe generated path: {}", relative.display());
    }
    let mut current = root.to_owned();
    for component in relative.components() {
        let Component::Normal(component) = component else {
            unreachable!();
        };
        current.push(component);
        if let Ok(metadata) = fs::symlink_metadata(&current) {
            if metadata.file_type().is_symlink() {
                bail!("generated path crosses symlink: {}", current.display());
            }
        }
    }
    Ok(current)
}

fn hex_sha256(value: &[u8]) -> String {
    Sha256::digest(value)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn target_rejects_parent_and_symlink_escape() {
        let root = tempfile::tempdir().unwrap();
        let canonical = root.path().canonicalize().unwrap();
        assert!(safe_target(&canonical, "../outside.ts").is_err());
        #[cfg(unix)]
        {
            std::os::unix::fs::symlink("/tmp", root.path().join("linked")).unwrap();
            assert!(safe_target(&canonical, "linked/file.ts").is_err());
        }
    }

    #[test]
    fn hash_is_stable() {
        assert_eq!(
            hex_sha256(b"nlab"),
            "72581ec52beac7983d521132b4d7c4730e4905bcb53b224274efbf109962134c"
        );
    }

    #[test]
    fn legacy_orval_header_is_owned_but_plain_source_is_not() {
        assert!(is_owned_generated_source(
            "/**\n * Generated by orval 🍺\n * Do not edit manually.\n */\nexport {}\n"
        ));
        assert!(!is_owned_generated_source(
            "export const handWritten = true;\n"
        ));
    }

    #[test]
    fn legacy_bridge_manifest_allows_only_its_listed_stale_file() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join("src/service")).unwrap();
        fs::write(
            root.path().join("src/service/legacy.ts"),
            "export const legacy = true;\n",
        )
        .unwrap();
        let previous = FrontendManifest {
            version: 1,
            layout: Some("service-paths".to_owned()),
            app_name: "app".to_owned(),
            branch: "feature".to_owned(),
            commit: "abc".to_owned(),
            openapi_sha256: "hash".to_owned(),
            api_files: vec!["src/service/legacy.ts".to_owned()],
            type_files: vec![],
            enum_files: vec![],
        };
        let current = FrontendManifest {
            layout: None,
            api_files: vec![],
            ..previous.clone()
        };
        assert!(preflight_stale_files(root.path(), Some(&previous), &current).is_ok());

        let unmanaged = FrontendManifest {
            layout: None,
            ..previous
        };
        assert!(preflight_stale_files(root.path(), Some(&unmanaged), &current).is_err());
    }

    #[test]
    fn generated_roots_drop_empty_descendants_only() {
        let root = tempfile::tempdir().unwrap();
        fs::create_dir_all(root.path().join("src/service/old/deep")).unwrap();
        fs::create_dir_all(root.path().join("src/service/kept")).unwrap();
        fs::write(root.path().join("src/service/kept/api.ts"), "export {}\n").unwrap();

        prune_empty_directories(root.path(), &["src/service".to_owned()]).unwrap();

        assert!(!root.path().join("src/service/old").exists());
        assert!(root.path().join("src/service/kept/api.ts").is_file());
        assert!(root.path().join("src/service").is_dir());
    }

    #[test]
    fn only_matching_root_openapi_is_removed() {
        let root = tempfile::tempdir().unwrap();
        fs::write(root.path().join("openapi.json"), "generated").unwrap();
        let hash = hex_sha256(b"generated");
        assert!(legacy_root_openapi_is_managed(root.path(), &hash, None).unwrap());
        assert!(!legacy_root_openapi_is_managed(root.path(), "other", None).unwrap());
    }
}
