use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::{Component, Path};

use anyhow::{Context, Result, bail};

use super::config::ProjectConfig;
use super::layout::{api_output_path, join_path, nearest_usage_directory, type_output_path};
use super::model::{
    CodedValue, ContractIr, Operation, ProvenanceStatus, Schema, SemanticPatch, TypeRef, WireValue,
};
use super::naming::{
    fqn_seed, lower_camel, shortest_unique_names_avoiding, upper_camel, without_enum_suffix,
    without_interface_prefix,
};
use super::openapi::{reachable_schemas, sanitize_identifier, schema_names};

const GENERATED_HEADER: &str = "// Generated by jt nlab-api. Do not edit manually.\n";

pub struct FrontendArtifact {
    pub files: BTreeMap<String, String>,
    pub api_files: Vec<String>,
    pub type_files: Vec<String>,
    pub enum_files: Vec<String>,
    pub managed_roots: Vec<String>,
}

#[derive(Clone, Debug)]
struct TypeTarget {
    name: String,
    path: String,
}

struct TargetPlan {
    base: HashMap<String, TypeTarget>,
    aliases: HashMap<String, HashMap<String, TypeTarget>>,
    data: HashMap<String, TypeTarget>,
    enums_by_patch: HashMap<String, TypeTarget>,
    enums_by_field: HashMap<String, TypeTarget>,
    enum_definitions: BTreeMap<String, (TypeTarget, Vec<CodedValue>)>,
}

pub fn generate(ir: &ContractIr, config: &ProjectConfig) -> Result<FrontendArtifact> {
    let plan = target_plan(ir, config)?;
    let mut files = BTreeMap::new();
    let mut type_files = Vec::new();
    let mut enum_files = Vec::new();

    for (fqn, schema) in &ir.schemas {
        let target = &plan.base[fqn];
        let empty_aliases = HashMap::new();
        let source = render_interface(
            schema,
            target,
            InterfaceRender {
                base_targets: &plan.base,
                aliases: &empty_aliases,
                operation: None,
                enum_targets: &plan.enums_by_patch,
                field_enum_targets: &plan.enums_by_field,
                config,
            },
        )?;
        insert_file(&mut files, &target.path, source)?;
        type_files.push(target.path.clone());
    }

    for (target, values) in plan.enum_definitions.values() {
        insert_file(&mut files, &target.path, render_enum(&target.name, values))?;
        enum_files.push(target.path.clone());
    }

    for operation in &ir.operations {
        let Some(alias_targets) = plan.aliases.get(&operation.key) else {
            continue;
        };
        for (fqn, target) in alias_targets {
            let schema = &ir.schemas[fqn];
            let source = render_interface(
                schema,
                target,
                InterfaceRender {
                    base_targets: &plan.base,
                    aliases: alias_targets,
                    operation: Some(operation),
                    enum_targets: &plan.enums_by_patch,
                    field_enum_targets: &plan.enums_by_field,
                    config,
                },
            )?;
            insert_file(&mut files, &target.path, source)?;
            type_files.push(target.path.clone());
        }
    }

    for operation in &ir.operations {
        let target = &plan.data[&operation.key];
        let aliases = plan
            .aliases
            .get(&operation.key)
            .cloned()
            .unwrap_or_default();
        let source = render_type_alias(target, &operation.response, &plan.base, &aliases, config);
        insert_file(&mut files, &target.path, source)?;
        type_files.push(target.path.clone());
    }

    let mut grouped: BTreeMap<String, Vec<&Operation>> = BTreeMap::new();
    for operation in &ir.operations {
        let relative = api_output_path(operation, &config.backend.contract_root)?;
        grouped
            .entry(join_path(
                &config.frontend.layout.implementation_dir,
                &relative,
            ))
            .or_default()
            .push(operation);
    }
    let mut api_files = Vec::new();
    for (path, mut operations) in grouped {
        operations.sort_by(|left, right| left.key.cmp(&right.key));
        let source = render_api_file(&path, &operations, &plan.base, &plan.data, config)?;
        insert_file(&mut files, &path, source)?;
        api_files.push(path);
    }
    type_files.sort();
    type_files.dedup();
    enum_files.sort();
    enum_files.dedup();
    api_files.sort();
    validate_imports(&files, config)?;
    Ok(FrontendArtifact {
        files,
        api_files,
        type_files,
        enum_files,
        managed_roots: vec![
            config.frontend.layout.implementation_dir.clone(),
            config.frontend.layout.types_dir.clone(),
            config.frontend.layout.enums_dir.clone(),
        ],
    })
}

fn target_plan(ir: &ContractIr, config: &ProjectConfig) -> Result<TargetPlan> {
    let base_names = schema_names(&ir.schemas);
    let usage_directories = schema_usage_directories(ir, &config.backend.contract_root)?;
    let base = ir
        .schemas
        .keys()
        .map(|fqn| {
            let directory =
                nearest_usage_directory(usage_directories.get(fqn).cloned().unwrap_or_default());
            let name = base_names[fqn].clone();
            (
                fqn.clone(),
                TypeTarget {
                    path: join_path(
                        &join_path(&config.frontend.layout.types_dir, &directory),
                        &format!("{}.ts", lower_camel(&name)),
                    ),
                    name,
                },
            )
        })
        .collect::<HashMap<_, _>>();
    let reserved = base_names.values().cloned().collect::<BTreeSet<_>>();
    let mut seeds = BTreeMap::<String, Vec<String>>::new();
    let mut alias_fqns = HashMap::<String, BTreeSet<String>>::new();
    for operation in &ir.operations {
        if operation
            .semantic_patches
            .iter()
            .any(|patch| patch.status == ProvenanceStatus::Closed && !patch.values.is_empty())
        {
            let reachable = reachable_schemas(&operation.response, &ir.schemas);
            for fqn in &reachable {
                seeds.insert(
                    alias_symbol(&operation.key, fqn),
                    vec![
                        without_interface_prefix(&operation.facade_name).to_owned(),
                        operation.method_name.clone(),
                        ir.schemas[fqn].name.clone(),
                    ],
                );
            }
            alias_fqns.insert(operation.key.clone(), reachable);
        }
        seeds.insert(
            data_symbol(&operation.key),
            vec![
                without_interface_prefix(&operation.facade_name).to_owned(),
                operation.method_name.clone(),
                "Data".to_owned(),
            ],
        );
    }

    let mut enum_values = BTreeMap::<String, Vec<CodedValue>>::new();
    let mut enum_usages = HashMap::<String, BTreeSet<String>>::new();
    let mut patch_enums = HashMap::<String, String>::new();
    let mut field_enums = HashMap::<String, String>::new();
    for operation in &ir.operations {
        let directory = type_output_path(operation, &config.backend.contract_root)?;
        for patch in operation
            .semantic_patches
            .iter()
            .filter(|patch| patch.status == ProvenanceStatus::Closed && !patch.values.is_empty())
        {
            let identity = enum_identity(patch);
            if let Some(existing) = enum_values.get(&identity) {
                if existing != &patch.values {
                    bail!("enum evidence changed for {identity} within one contract snapshot");
                }
            } else {
                enum_values.insert(identity.clone(), patch.values.clone());
                seeds.insert(enum_symbol(&identity), enum_seed(patch));
            }
            enum_usages
                .entry(identity.clone())
                .or_default()
                .insert(directory.clone());
            patch_enums.insert(patch_symbol(patch), identity);
        }
    }
    for (fqn, schema) in &ir.schemas {
        for field in &schema.fields {
            let Some(linked) = &field.linked_enum else {
                continue;
            };
            let identity = format!("{}#{}", linked.enum_fqn, linked.accessor);
            if let Some(existing) = enum_values.get(&identity) {
                if existing != &linked.values {
                    bail!("linked enum evidence changed for {identity} within one snapshot");
                }
            } else {
                enum_values.insert(identity.clone(), linked.values.clone());
                seeds.insert(
                    enum_symbol(&identity),
                    enum_seed_from_parts(&linked.enum_fqn, &linked.accessor, &field.name),
                );
            }
            enum_usages
                .entry(identity.clone())
                .or_default()
                .extend(usage_directories.get(fqn).cloned().unwrap_or_default());
            field_enums.insert(field_symbol(fqn, &field.name), identity);
        }
    }

    let names = shortest_unique_names_avoiding(&seeds, &reserved);
    let mut aliases = HashMap::new();
    for operation in &ir.operations {
        let Some(fqns) = alias_fqns.get(&operation.key) else {
            continue;
        };
        let directory = join_path(
            &config.frontend.layout.types_dir,
            &type_output_path(operation, &config.backend.contract_root)?,
        );
        aliases.insert(
            operation.key.clone(),
            fqns.iter()
                .map(|fqn| {
                    let name = names[&alias_symbol(&operation.key, fqn)].clone();
                    (
                        fqn.clone(),
                        TypeTarget {
                            path: join_path(&directory, &format!("{}.ts", lower_camel(&name))),
                            name,
                        },
                    )
                })
                .collect(),
        );
    }
    let data = ir
        .operations
        .iter()
        .map(|operation| {
            let name = names[&data_symbol(&operation.key)].clone();
            let directory = join_path(
                &config.frontend.layout.types_dir,
                &type_output_path(operation, &config.backend.contract_root)?,
            );
            Ok((
                operation.key.clone(),
                TypeTarget {
                    path: join_path(&directory, &format!("{}.ts", lower_camel(&name))),
                    name,
                },
            ))
        })
        .collect::<Result<HashMap<_, _>>>()?;
    let enum_definitions = enum_values
        .into_iter()
        .map(|(identity, values)| {
            let name = names[&enum_symbol(&identity)].clone();
            let directory =
                nearest_usage_directory(enum_usages.get(&identity).cloned().unwrap_or_default());
            let target = TypeTarget {
                path: join_path(
                    &join_path(&config.frontend.layout.enums_dir, &directory),
                    &format!("{}.ts", lower_camel(&name)),
                ),
                name,
            };
            (identity, (target, values))
        })
        .collect::<BTreeMap<_, _>>();
    let enums_by_patch = patch_enums
        .into_iter()
        .map(|(patch, identity)| (patch, enum_definitions[&identity].0.clone()))
        .collect();
    let enums_by_field = field_enums
        .into_iter()
        .map(|(field, identity)| (field, enum_definitions[&identity].0.clone()))
        .collect();
    Ok(TargetPlan {
        base,
        aliases,
        data,
        enums_by_patch,
        enums_by_field,
        enum_definitions,
    })
}

fn schema_usage_directories(
    ir: &ContractIr,
    contract_root: &str,
) -> Result<HashMap<String, BTreeSet<String>>> {
    let mut usages = HashMap::<String, BTreeSet<String>>::new();
    for operation in &ir.operations {
        let directory = type_output_path(operation, contract_root)?;
        let mut schemas = reachable_schemas(&operation.response, &ir.schemas);
        if let Some(request) = &operation.request {
            schemas.extend(reachable_schemas(request, &ir.schemas));
        }
        for fqn in schemas {
            usages.entry(fqn).or_default().insert(directory.clone());
        }
    }
    Ok(usages)
}

fn alias_symbol(operation_key: &str, fqn: &str) -> String {
    format!("alias:{operation_key}:{fqn}")
}

fn data_symbol(operation_key: &str) -> String {
    format!("data:{operation_key}")
}

fn enum_symbol(identity: &str) -> String {
    format!("enum:{identity}")
}

fn field_symbol(schema_fqn: &str, field_name: &str) -> String {
    format!("field:{schema_fqn}:{field_name}")
}

fn enum_identity(patch: &SemanticPatch) -> String {
    format!(
        "{}#{}",
        patch
            .enum_fqn
            .as_deref()
            .unwrap_or(&patch.target.schema_fqn),
        patch
            .accessor
            .as_deref()
            .unwrap_or(&patch.target.field_name)
    )
}

fn enum_seed(patch: &SemanticPatch) -> Vec<String> {
    let owner = patch
        .enum_fqn
        .as_deref()
        .unwrap_or(&patch.target.schema_fqn);
    enum_seed_from_parts(
        owner,
        patch
            .accessor
            .as_deref()
            .unwrap_or(&patch.target.field_name),
        &patch.target.field_name,
    )
}

fn enum_seed_from_parts(owner: &str, accessor: &str, field_name: &str) -> Vec<String> {
    let mut seed = fqn_seed(owner);
    if let Some(last) = seed.last_mut() {
        *last = without_enum_suffix(last).to_owned();
    }
    let accessor = accessor
        .strip_prefix("get")
        .or_else(|| accessor.strip_prefix("is"))
        .filter(|value| !value.is_empty())
        .unwrap_or(field_name);
    let owner_name = seed.last().map(String::as_str).unwrap_or_default();
    if let Some(suffix) = remove_owner_overlap(owner_name, accessor) {
        seed.push(suffix.to_owned());
    }
    seed
}

fn remove_owner_overlap<'a>(owner: &str, accessor: &'a str) -> Option<&'a str> {
    let overlap = accessor
        .char_indices()
        .filter(|(index, character)| *index > 0 && character.is_ascii_uppercase())
        .map(|(index, _)| index)
        .chain(std::iter::once(accessor.len()))
        .filter(|index| owner.ends_with(&accessor[..*index]))
        .max()
        .unwrap_or(0);
    let suffix = &accessor[overlap..];
    (!suffix.is_empty()).then_some(suffix)
}

fn patch_symbol(patch: &SemanticPatch) -> String {
    format!(
        "{}:{}:{}",
        patch.target.operation_key, patch.target.schema_fqn, patch.target.field_path
    )
}

fn validate_imports(files: &BTreeMap<String, String>, config: &ProjectConfig) -> Result<()> {
    for (path, source) in files {
        for line in source
            .lines()
            .filter(|line| line.starts_with("import type "))
        {
            let Some((_, specifier)) = line.rsplit_once(" from ") else {
                bail!("invalid generated import in {path}: {line}");
            };
            let specifier = serde_json::from_str::<String>(specifier.trim_end_matches(';'))
                .map_err(|error| anyhow::anyhow!("invalid generated import in {path}: {error}"))?;
            let target = resolve_generated_module(path, &specifier, config)?;
            if !files.contains_key(&target) {
                bail!("generated import target missing: {path} -> {specifier} ({target})");
            }
        }
    }
    Ok(())
}

fn resolve_generated_module(
    from_file: &str,
    specifier: &str,
    config: &ProjectConfig,
) -> Result<String> {
    for (alias, root) in [
        (
            &config.frontend.aliases.implementation,
            &config.frontend.layout.implementation_dir,
        ),
        (
            &config.frontend.aliases.types,
            &config.frontend.layout.types_dir,
        ),
        (
            &config.frontend.aliases.enums,
            &config.frontend.layout.enums_dir,
        ),
    ] {
        if let Some(relative) = specifier.strip_prefix(&format!("{alias}/")) {
            return Ok(format!("{}.ts", join_path(root, relative)));
        }
    }
    resolve_relative_module(from_file, specifier)
}

fn resolve_relative_module(from_file: &str, specifier: &str) -> Result<String> {
    if !specifier.starts_with('.') {
        bail!("generated import must be relative: {specifier}");
    }
    let mut components = normal_components(
        Path::new(from_file)
            .parent()
            .unwrap_or_else(|| Path::new("")),
    );
    for component in Path::new(specifier).components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                if components.pop().is_none() {
                    bail!("generated import escapes output root: {from_file} -> {specifier}");
                }
            }
            Component::Normal(value) => components.push(value.to_string_lossy().into_owned()),
            _ => bail!("invalid generated import: {specifier}"),
        }
    }
    Ok(format!("{}.ts", components.join("/")))
}

struct InterfaceRender<'a> {
    base_targets: &'a HashMap<String, TypeTarget>,
    aliases: &'a HashMap<String, TypeTarget>,
    operation: Option<&'a Operation>,
    enum_targets: &'a HashMap<String, TypeTarget>,
    field_enum_targets: &'a HashMap<String, TypeTarget>,
    config: &'a ProjectConfig,
}

fn render_interface(
    schema: &Schema,
    target: &TypeTarget,
    render: InterfaceRender<'_>,
) -> Result<String> {
    let InterfaceRender {
        base_targets,
        aliases,
        operation,
        enum_targets,
        field_enum_targets,
        config,
    } = render;
    let mut imports = BTreeMap::<String, BTreeSet<String>>::new();
    let patches = operation
        .map(|operation| {
            operation
                .semantic_patches
                .iter()
                .filter(|patch| {
                    patch.target.schema_fqn == schema.fqn
                        && patch.status == ProvenanceStatus::Closed
                })
                .map(|patch| (patch.target.field_name.as_str(), patch))
                .collect::<HashMap<_, _>>()
        })
        .unwrap_or_default();
    let mut fields = String::new();
    for field in &schema.fields {
        let type_name = if let Some(patch) = patches.get(field.name.as_str()) {
            let enum_target = enum_targets
                .get(&patch_symbol(patch))
                .with_context(|| format!("enum target missing for {}", patch_symbol(patch)))?;
            imports
                .entry(import_specifier(&target.path, &enum_target.path, config))
                .or_default()
                .insert(enum_target.name.clone());
            enum_target.name.clone()
        } else if let Some(enum_target) =
            field_enum_targets.get(&field_symbol(&schema.fqn, &field.name))
        {
            imports
                .entry(import_specifier(&target.path, &enum_target.path, config))
                .or_default()
                .insert(enum_target.name.clone());
            enum_target.name.clone()
        } else {
            type_expression(
                &field.java_type,
                target,
                base_targets,
                aliases,
                &mut imports,
                config,
            )
        };
        if let Some(description) = &field.description {
            fields.push_str(&render_doc(description, "  "));
        }
        fields.push_str(&format!(
            "  {}{}: {};\n",
            safe_property(&field.name),
            if field.optional { "?" } else { "" },
            type_name
        ));
    }
    let mut output = String::from(GENERATED_HEADER);
    output.push_str(&render_imports(imports));
    if !output.ends_with("\n\n") {
        output.push('\n');
    }
    if let Some(description) = &schema.description {
        output.push_str(&render_doc(description, ""));
    }
    output.push_str(&format!(
        "export interface {} {{\n{fields}}}\n",
        target.name
    ));
    Ok(output)
}

fn render_type_alias(
    target: &TypeTarget,
    type_ref: &TypeRef,
    base_targets: &HashMap<String, TypeTarget>,
    aliases: &HashMap<String, TypeTarget>,
    config: &ProjectConfig,
) -> String {
    let mut imports = BTreeMap::<String, BTreeSet<String>>::new();
    let expression = type_expression(
        type_ref,
        target,
        base_targets,
        aliases,
        &mut imports,
        config,
    );
    format!(
        "{GENERATED_HEADER}{}\nexport type {} = {};\n",
        render_imports(imports),
        target.name,
        expression
    )
}

fn render_api_file(
    path: &str,
    operations: &[&Operation],
    base_targets: &HashMap<String, TypeTarget>,
    data_targets: &HashMap<String, TypeTarget>,
    config: &ProjectConfig,
) -> Result<String> {
    let mut imports = BTreeMap::<String, BTreeSet<String>>::new();
    let current = TypeTarget {
        name: String::new(),
        path: path.to_owned(),
    };
    let mut method_names = BTreeSet::new();
    let mut bodies = String::new();
    for operation in operations {
        let export_name = lower_camel(&operation.method_name);
        if !method_names.insert(export_name.clone()) {
            bail!("generated method collision in {path}: {export_name}");
        }
        let data = &data_targets[&operation.key];
        let url_function = url_function_name(&export_name);
        imports
            .entry(import_specifier(path, &data.path, config))
            .or_default()
            .insert(data.name.clone());
        let request = operation.request.as_ref().map(|request| {
            let mut request_imports = BTreeMap::<String, BTreeSet<String>>::new();
            let type_name = type_expression(
                request,
                &current,
                base_targets,
                &HashMap::new(),
                &mut request_imports,
                config,
            );
            merge_imports(&mut imports, request_imports);
            let parameter = lower_camel(request.simple_name());
            (parameter, type_name)
        });
        if let Some(description) = &operation.description {
            bodies.push_str(&render_doc(description, ""));
        }
        bodies.push_str(&format!(
            "export const {url_function} = (): string => {};\n\n",
            ts_string(&operation.route.path)
        ));
        let parameters = request.as_ref().map_or_else(
            || {
                format!(
                    "options?: SecondParameter<typeof {}<{}>>",
                    config.frontend.request.export, data.name
                )
            },
            |(parameter, type_name)| {
                format!(
                    "{parameter}: {type_name},\n  options?: SecondParameter<typeof {}<{}>>",
                    config.frontend.request.export, data.name
                )
            },
        );
        let payload = request.as_ref().map_or_else(String::new, |(parameter, _)| {
            if operation.route.method.eq_ignore_ascii_case("GET") {
                format!("\n      params: {parameter},")
            } else {
                format!(
                    "\n      headers: {{ 'Content-Type': 'application/json' }},\n      data: {parameter},"
                )
            }
        });
        bodies.push_str(&format!(
            "export function {export_name}(\n  {parameters},\n): Promise<{}> {{\n  return {}<{}>(\n    {{\n      url: {url_function}(),\n      method: {},{payload}\n    }},\n    options,\n  );\n}}\n\n",
            data.name,
            config.frontend.request.export,
            data.name,
            ts_string(&operation.route.method.to_ascii_uppercase()),
        ));
    }
    Ok(format!(
        "{GENERATED_HEADER}{}import {{ {} }} from {};\n\ntype SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];\n\n{bodies}",
        render_imports(imports),
        config.frontend.request.export,
        ts_string(&config.frontend.request.module),
    ))
}

fn url_function_name(method: &str) -> String {
    if method
        .strip_prefix("get")
        .and_then(|rest| rest.chars().next())
        .is_some_and(|first| first.is_ascii_uppercase())
    {
        format!("{method}Url")
    } else {
        format!("get{}Url", upper_camel(method))
    }
}

fn type_expression(
    type_ref: &TypeRef,
    current: &TypeTarget,
    base_targets: &HashMap<String, TypeTarget>,
    aliases: &HashMap<String, TypeTarget>,
    imports: &mut BTreeMap<String, BTreeSet<String>>,
    config: &ProjectConfig,
) -> String {
    let scalar = match type_ref.simple_name() {
        "String" | "CharSequence" | "char" | "Character" | "Long" | "long" | "BigInteger"
        | "Date" | "LocalDate" | "LocalDateTime" | "Instant" | "Timestamp" => Some("string"),
        "Integer" | "int" | "Short" | "short" | "Byte" | "byte" | "Double" | "double" | "Float"
        | "float" | "BigDecimal" => Some("number"),
        "Boolean" | "boolean" => Some("boolean"),
        "Void" | "void" => Some("void"),
        "Object" | "JSONObject" => Some("unknown"),
        _ => None,
    };
    let mut result = if let Some(scalar) = scalar {
        scalar.to_owned()
    } else if is_collection(type_ref.simple_name()) {
        format!(
            "{}[]",
            type_ref
                .arguments
                .first()
                .map(|item| type_expression(item, current, base_targets, aliases, imports, config))
                .unwrap_or_else(|| "unknown".to_owned())
        )
    } else if matches!(type_ref.simple_name(), "PageList" | "Page" | "PageResult") {
        let item = type_ref
            .arguments
            .last()
            .map(|item| type_expression(item, current, base_targets, aliases, imports, config))
            .unwrap_or_else(|| "unknown".to_owned());
        format!("{{ totalNum: number; list: {item}[] }}")
    } else if matches!(
        type_ref.simple_name(),
        "Map" | "HashMap" | "LinkedHashMap" | "TreeMap"
    ) {
        let value = type_ref
            .arguments
            .last()
            .map(|value| type_expression(value, current, base_targets, aliases, imports, config))
            .unwrap_or_else(|| "unknown".to_owned());
        format!("Record<string, {value}>")
    } else if type_ref.simple_name() == "Optional" {
        let value = type_ref
            .arguments
            .first()
            .map(|value| type_expression(value, current, base_targets, aliases, imports, config))
            .unwrap_or_else(|| "unknown".to_owned());
        format!("{value} | undefined")
    } else {
        let fqn = type_ref.name.replace("::", ".");
        let target = aliases.get(&fqn).or_else(|| base_targets.get(&fqn));
        if let Some(target) = target {
            if target.path != current.path {
                imports
                    .entry(import_specifier(&current.path, &target.path, config))
                    .or_default()
                    .insert(target.name.clone());
            }
            target.name.clone()
        } else {
            "unknown".to_owned()
        }
    };
    for _ in 0..type_ref.array_depth {
        result = format!("{result}[]");
    }
    result
}

fn render_enum(name: &str, values: &[CodedValue]) -> String {
    let entries = values
        .iter()
        .map(|value| {
            let key = value.key.clone().unwrap_or_else(|| enum_key(&value.value));
            format!(
                "  /** {} */\n  {}: {},\n",
                value.label.replace("*/", "* /"),
                sanitize_identifier(&key),
                wire_literal(&value.value)
            )
        })
        .collect::<String>();
    format!(
        "{GENERATED_HEADER}\nexport const {name} = {{\n{entries}}} as const;\n\nexport type {name} = typeof {name}[keyof typeof {name}];\n"
    )
}

fn render_imports(imports: BTreeMap<String, BTreeSet<String>>) -> String {
    imports
        .into_iter()
        .map(|(path, names)| {
            format!(
                "import type {{ {} }} from {};\n",
                names.into_iter().collect::<Vec<_>>().join(", "),
                ts_string(&path)
            )
        })
        .collect()
}

fn merge_imports(
    target: &mut BTreeMap<String, BTreeSet<String>>,
    source: BTreeMap<String, BTreeSet<String>>,
) {
    for (path, names) in source {
        target.entry(path).or_default().extend(names);
    }
}

fn render_doc(value: &str, indent: &str) -> String {
    let lines = value
        .replace("*/", "* /")
        .lines()
        .map(|line| format!("{indent} * {line}\n"))
        .collect::<String>();
    format!("{indent}/**\n{lines}{indent} */\n")
}

fn insert_file(files: &mut BTreeMap<String, String>, path: &str, source: String) -> Result<()> {
    if let Some(existing) = files.insert(path.to_owned(), source.clone()) {
        if existing != source {
            bail!("generated file collision: {path}");
        }
    }
    Ok(())
}

fn relative_import(from_file: &str, to_file: &str) -> String {
    let from = Path::new(from_file)
        .parent()
        .unwrap_or_else(|| Path::new(""));
    let to = Path::new(to_file).with_extension("");
    let from_parts = normal_components(from);
    let to_parts = normal_components(&to);
    let common = from_parts
        .iter()
        .zip(&to_parts)
        .take_while(|(left, right)| left == right)
        .count();
    let mut parts = vec![".."; from_parts.len() - common];
    parts.extend(to_parts[common..].iter().map(String::as_str));
    let value = parts.join("/");
    if value.starts_with('.') {
        value
    } else {
        format!("./{value}")
    }
}

fn import_specifier(from_file: &str, to_file: &str, config: &ProjectConfig) -> String {
    for (root, alias) in [
        (
            &config.frontend.layout.types_dir,
            &config.frontend.aliases.types,
        ),
        (
            &config.frontend.layout.enums_dir,
            &config.frontend.aliases.enums,
        ),
        (
            &config.frontend.layout.implementation_dir,
            &config.frontend.aliases.implementation,
        ),
    ] {
        if let Some(relative) = to_file.strip_prefix(&format!("{root}/")) {
            return format!(
                "{alias}/{}",
                relative.strip_suffix(".ts").unwrap_or(relative)
            );
        }
    }
    relative_import(from_file, to_file)
}

fn normal_components(path: &Path) -> Vec<String> {
    path.components()
        .filter_map(|component| match component {
            Component::Normal(value) => Some(value.to_string_lossy().into_owned()),
            _ => None,
        })
        .collect()
}

fn safe_property(value: &str) -> String {
    if is_identifier(value) {
        value.to_owned()
    } else {
        ts_string(value)
    }
}

fn is_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars.next().is_some_and(|character| {
        character == '_' || character == '$' || character.is_ascii_alphabetic()
    }) && chars
        .all(|character| character == '_' || character == '$' || character.is_ascii_alphanumeric())
}

fn enum_key(value: &WireValue) -> String {
    match value {
        WireValue::String(value) => value
            .to_ascii_uppercase()
            .replace(|character: char| !character.is_ascii_alphanumeric(), "_"),
        WireValue::Number(value) => format!("VALUE_{value}"),
    }
}

fn wire_literal(value: &WireValue) -> String {
    match value {
        WireValue::String(value) => ts_string(value),
        WireValue::Number(value) => value.to_string(),
    }
}

fn ts_string(value: &str) -> String {
    serde_json::to_string(value).expect("serialize TypeScript string")
}

fn is_collection(name: &str) -> bool {
    matches!(
        name,
        "List" | "Set" | "Collection" | "ArrayList" | "LinkedList" | "HashSet" | "Iterable"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config() -> ProjectConfig {
        serde_json::from_value(serde_json::json!({
            "version": 1,
            "backend": {
                "repoPath": "/backend",
                "branch": "feature",
                "appName": "app",
                "contractRoot": "contract/src/main/java/p/contract"
            },
            "frontend": {
                "sourceRoot": "src",
                "buildTool": {
                    "kind": "vite",
                    "configPath": "vite.config.ts",
                    "testConfigs": []
                },
                "tsconfigPath": "tsconfig.json",
                "request": {
                    "module": "@/utils/request",
                    "export": "nlabRequest",
                    "responseMode": "unwrapped"
                },
                "response": {
                    "successCode": "0",
                    "codeFields": ["code", "respCode"],
                    "dataFields": ["data", "respData"]
                },
                "layout": {
                    "preset": "service",
                    "implementationDir": "src/service",
                    "typesDir": "src/types/service-type",
                    "enumsDir": "src/types/service-enums"
                },
                "aliases": {
                    "implementation": "@service",
                    "types": "@service-types",
                    "enums": "@service-enums"
                }
            }
        }))
        .unwrap()
    }

    #[test]
    fn relative_imports_are_lexical_and_extensionless() {
        assert_eq!(
            relative_import("api/recycle/query.ts", "types/share/order.ts"),
            "../../types/share/order"
        );
        assert_eq!(
            relative_import("types/recycle/query.ts", "types/recycle/order.ts"),
            "./order"
        );
    }

    #[test]
    fn word_conversion_keeps_initialisms_stable_enough() {
        assert_eq!(
            upper_camel("queryRecycleOrderList"),
            "QueryRecycleOrderList"
        );
        assert_eq!(lower_camel("IRecycleQueryFacade"), "iRecycleQueryFacade");
        assert_eq!(
            url_function_name("getRefurbOrderTypeTabs"),
            "getRefurbOrderTypeTabsUrl"
        );
        assert_eq!(url_function_name("queryOrder"), "getQueryOrderUrl");
        assert_eq!(
            remove_owner_overlap("RecycleDetailAction", "ActionCode"),
            Some("Code")
        );
        assert_eq!(
            remove_owner_overlap("RefurbButton", "ActionCode"),
            Some("ActionCode")
        );
    }

    #[test]
    fn declared_values_do_not_create_strict_shared_enum() {
        let schema = Schema {
            fqn: "p.BizButton".to_owned(),
            name: "BizButton".to_owned(),
            source_path: "BizButton.java".to_owned(),
            description: None,
            fields: vec![super::super::model::Field {
                name: "actionCode".to_owned(),
                java_type: TypeRef {
                    name: "String".to_owned(),
                    arguments: vec![],
                    array_depth: 0,
                },
                optional: false,
                description: None,
                declared_values: Some(super::super::model::CodedValues {
                    name: "ActionCodeValues".to_owned(),
                    source: super::super::model::CodedValueSource::Comment,
                    values: vec![super::super::model::CodedValue {
                        value: WireValue::String("wrong".to_owned()),
                        key: None,
                        label: "注释值".to_owned(),
                    }],
                }),
                linked_enum: None,
            }],
        };
        let target = TypeTarget {
            name: "BizButton".to_owned(),
            path: "types/bizButton.ts".to_owned(),
        };

        let base_targets = HashMap::new();
        let aliases = HashMap::new();
        let enum_targets = HashMap::new();
        let field_enum_targets = HashMap::new();
        let config = config();
        let source = render_interface(
            &schema,
            &target,
            InterfaceRender {
                base_targets: &base_targets,
                aliases: &aliases,
                operation: None,
                enum_targets: &enum_targets,
                field_enum_targets: &field_enum_targets,
                config: &config,
            },
        )
        .unwrap();

        assert!(source.contains("actionCode: string;"));
        assert!(!source.contains("export const BizButtonActionCode"));
    }

    #[test]
    fn generation_uses_facade_layout_request_adapter_and_separate_enum() {
        let ir = serde_json::from_value::<ContractIr>(serde_json::json!({
            "target": {
                "appName": "app",
                "branch": "feature",
                "commit": "abc",
                "codegraphVersion": "1",
                "codegraphExtractionVersion": "1"
            },
            "operations": [{
                "key": "IGoodsQueryFacade#queryButtons",
                "facadeName": "IGoodsQueryFacade",
                "facadeFqn": "p.contract.checkapp.IGoodsQueryFacade",
                "methodName": "queryButtons",
                "signature": "BizButton queryButtons()",
                "description": null,
                "contractSource": "contract/src/main/java/p/contract/checkapp/IGoodsQueryFacade.java",
                "request": null,
                "response": { "name": "p.BizButton", "arguments": [], "arrayDepth": 0 },
                "requestSchema": null,
                "responseSchema": "p.BizButton",
                "service": null,
                "route": {
                    "status": "placeholder",
                    "source": "placeholder",
                    "method": "POST",
                    "path": "/query",
                    "host": null
                },
                "semanticPatches": [{
                    "target": {
                        "operationKey": "IGoodsQueryFacade#queryButtons",
                        "schemaFqn": "p.BizButton",
                        "fieldPath": "actionCode",
                        "fieldName": "actionCode"
                    },
                    "status": "closed",
                    "enumFqn": "p.RefurbButtonEnum",
                    "enumSource": "RefurbButtonEnum.java",
                    "accessor": "getActionCode",
                    "values": [{
                        "value": "start_refurb",
                        "key": "START_REFURB",
                        "label": "去整备"
                    }],
                    "evidence": ["test"],
                    "warning": null
                }],
                "warnings": []
            }],
            "schemas": {
                "p.BizButton": {
                    "fqn": "p.BizButton",
                    "name": "BizButton",
                    "sourcePath": "BizButton.java",
                    "description": null,
                    "fields": [{
                        "name": "actionCode",
                        "javaType": { "name": "String", "arguments": [], "arrayDepth": 0 },
                        "optional": false,
                        "description": null,
                        "declaredValues": null
                    }]
                }
            }
        }))
        .unwrap();

        let artifact = generate(&ir, &config()).unwrap();
        let api = &artifact.files["src/service/checkapp/goodsQueryFacade.ts"];
        assert!(api.contains("from \"@/utils/request\""));
        assert!(api.contains("return nlabRequest<"));
        assert!(!api.contains("fetch("));
        assert_eq!(artifact.enum_files.len(), 1);
        let enum_source = &artifact.files[&artifact.enum_files[0]];
        assert!(enum_source.contains("START_REFURB: \"start_refurb\""));
        let patched_type = artifact
            .files
            .values()
            .find(|source| source.contains("actionCode: ActionCode"))
            .expect("patched operation type");
        assert!(patched_type.contains("@service-enums/checkapp/goodsQueryFacade/actionCode"));
    }
}
