use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::{Component, Path};

use anyhow::{Context, Result, bail};

use super::config::ProjectConfig;
use super::layout::{api_output_path, join_path, nearest_usage_directory, type_output_path};
use super::model::{
    CodedValue, ContractIr, FieldSource, InputLocation, Operation, Schema, SemanticPatch, TypeRef,
    WireValue,
};
use super::naming::{
    fqn_seed, lower_camel, shortest_unique_names_avoiding, upper_camel, without_enum_suffix,
};
use super::openapi::{SchemaPlan, enum_identity, sanitize_identifier, schema_names, schema_plan};

const GENERATED_HEADER: &str = "// Generated by jt nlab-api. Do not edit manually.\n";

pub struct FrontendArtifact {
    pub files: BTreeMap<String, String>,
    pub api_files: Vec<String>,
    pub type_files: Vec<String>,
    pub enum_files: Vec<String>,
    pub managed_roots: Vec<String>,
}

#[derive(Clone, Debug)]
struct TypeTarget {
    name: String,
    path: String,
    type_parameters: Vec<String>,
}

struct TargetPlan {
    schemas: SchemaPlan,
    base: HashMap<String, TypeTarget>,
    aliases: HashMap<String, HashMap<String, TypeTarget>>,
    enums_by_patch: HashMap<String, TypeTarget>,
    enum_definitions: BTreeMap<String, (TypeTarget, Vec<CodedValue>)>,
}

pub fn generate(ir: &ContractIr, config: &ProjectConfig) -> Result<FrontendArtifact> {
    config.validate()?;
    let plan = target_plan(ir, config)?;
    let mut files = BTreeMap::new();
    let mut type_files = Vec::new();
    let mut enum_files = Vec::new();

    let empty_aliases = HashMap::new();
    for variant in &plan.schemas.variants {
        let operation = variant.operation.map(|index| &ir.operations[index]);
        let aliases = operation
            .and_then(|operation| plan.aliases.get(&variant.source.operation_key(operation)))
            .unwrap_or(&empty_aliases);
        let target = aliases
            .get(&variant.fqn)
            .unwrap_or_else(|| &plan.base[&variant.fqn]);
        let source = render_interface(
            &ir.schemas[&variant.fqn],
            target,
            InterfaceRender {
                base_targets: &plan.base,
                aliases,
                operation,
                source: variant.source,
                optional_fields: variant.optional_fields,
                enum_targets: &plan.enums_by_patch,
                config,
            },
        )?;
        insert_file(&mut files, &target.path, source)?;
        type_files.push(target.path.clone());
    }

    for (identity, (target, values)) in &plan.enum_definitions {
        insert_file(
            &mut files,
            &target.path,
            render_enum(&target.name, values, identity, config.enum_erasable),
        )?;
        enum_files.push(target.path.clone());
    }

    let mut grouped: BTreeMap<String, Vec<&Operation>> = BTreeMap::new();
    for operation in &ir.operations {
        let relative = api_output_path(operation, &config.backend.contract_roots)?;
        grouped
            .entry(join_path(
                &config.frontend.layout.implementation_dir,
                &relative,
            ))
            .or_default()
            .push(operation);
    }
    let mut api_files = Vec::new();
    for (path, mut operations) in grouped {
        operations.sort_by(|left, right| left.key.cmp(&right.key));
        let source = render_api_file(&path, &operations, &plan.base, &plan.aliases, config)?;
        insert_file(&mut files, &path, source)?;
        api_files.push(path);
    }
    type_files.sort();
    type_files.dedup();
    enum_files.sort();
    enum_files.dedup();
    api_files.sort();
    validate_imports(&files, config)?;
    Ok(FrontendArtifact {
        files,
        api_files,
        type_files,
        enum_files,
        managed_roots: vec![
            config.frontend.layout.implementation_dir.clone(),
            config.frontend.layout.types_dir.clone(),
            config.frontend.layout.enums_dir.clone(),
        ],
    })
}

fn target_plan(ir: &ContractIr, config: &ProjectConfig) -> Result<TargetPlan> {
    let schemas = schema_plan(ir);
    let base_names = schema_names(&ir.schemas);
    let targets = schemas
        .variants
        .iter()
        .map(|variant| {
            let directories = variant
                .usages
                .iter()
                .map(|index| {
                    type_output_path(&ir.operations[*index], &config.backend.contract_roots)
                })
                .collect::<Result<BTreeSet<_>>>()?;
            let directory = nearest_usage_directory(directories);
            Ok((
                variant.name.clone(),
                TypeTarget {
                    path: join_path(
                        &join_path(&config.frontend.layout.types_dir, &directory),
                        &format!("{}.ts", lower_camel(&variant.name)),
                    ),
                    name: variant.name.clone(),
                    type_parameters: ir.schemas[&variant.fqn].type_parameters.clone(),
                },
            ))
        })
        .collect::<Result<HashMap<_, _>>>()?;
    let base = schemas
        .variants
        .iter()
        .filter(|variant| variant.name == base_names[&variant.fqn])
        .map(|variant| (variant.fqn.clone(), targets[&variant.name].clone()))
        .collect();
    let aliases = schemas
        .aliases
        .iter()
        .map(|(operation, names)| {
            (
                operation.clone(),
                names
                    .iter()
                    .map(|(fqn, name)| (fqn.clone(), targets[name].clone()))
                    .collect(),
            )
        })
        .collect();
    let reserved = targets.keys().cloned().collect::<BTreeSet<_>>();
    let mut seeds = BTreeMap::<String, Vec<String>>::new();

    let mut enum_values = BTreeMap::<String, Vec<CodedValue>>::new();
    let mut enum_usages = HashMap::<String, BTreeSet<String>>::new();
    let mut patch_enums = HashMap::<String, String>::new();
    for operation in &ir.operations {
        let directory = type_output_path(operation, &config.backend.contract_roots)?;
        for patch in operation
            .semantic_patches
            .iter()
            .filter(|patch| patch.associated_values().is_some())
        {
            let values = patch.associated_values().expect("associated enum values");
            let identity = enum_identity(patch);
            if let Some(existing) = enum_values.get(&identity) {
                if existing != values {
                    bail!("enum evidence changed for {identity} within one contract snapshot");
                }
            } else {
                enum_values.insert(identity.clone(), values.to_vec());
                seeds.insert(enum_symbol(&identity), enum_seed(patch));
            }
            enum_usages
                .entry(identity.clone())
                .or_default()
                .insert(directory.clone());
            if patch.associated_values().is_some() {
                patch_enums.insert(patch_symbol(patch), identity);
            }
        }
    }
    let names = shortest_unique_names_avoiding(&seeds, &reserved);
    let enum_definitions = enum_values
        .into_iter()
        .map(|(identity, values)| {
            let name = names[&enum_symbol(&identity)].clone();
            let directory =
                nearest_usage_directory(enum_usages.get(&identity).cloned().unwrap_or_default());
            let target = TypeTarget {
                path: join_path(
                    &join_path(&config.frontend.layout.enums_dir, &directory),
                    &format!("{}.ts", lower_camel(&name)),
                ),
                name,
                type_parameters: Vec::new(),
            };
            (identity, (target, values))
        })
        .collect::<BTreeMap<_, _>>();
    let enums_by_patch = patch_enums
        .into_iter()
        .map(|(patch, identity)| (patch, enum_definitions[&identity].0.clone()))
        .collect();
    Ok(TargetPlan {
        schemas,
        base,
        aliases,
        enums_by_patch,
        enum_definitions,
    })
}

fn enum_symbol(identity: &str) -> String {
    format!("enum:{identity}")
}

fn enum_seed(patch: &SemanticPatch) -> Vec<String> {
    let owner = patch
        .enum_fqn
        .as_deref()
        .unwrap_or(&patch.target.schema_fqn);
    enum_seed_from_parts(
        owner,
        patch
            .accessor
            .as_deref()
            .unwrap_or(&patch.target.field_name),
    )
}

fn enum_seed_from_parts(owner: &str, accessor: &str) -> Vec<String> {
    let mut seed = fqn_seed(owner);
    if let Some(last) = seed.last_mut() {
        *last = without_enum_suffix(last).to_owned();
    }
    let accessor = upper_camel(
        accessor
            .strip_prefix("get")
            .or_else(|| accessor.strip_prefix("is"))
            .filter(|value| !value.is_empty())
            .unwrap_or(accessor),
    );
    let owner_name = seed.last().cloned().unwrap_or_default();
    if let Some(suffix) = remove_owner_overlap(&owner_name, &accessor)
        && let Some(owner) = seed.last_mut()
    {
        owner.push_str(&upper_camel(suffix));
    }
    seed
}

fn remove_owner_overlap<'a>(owner: &str, accessor: &'a str) -> Option<&'a str> {
    let overlap = accessor
        .char_indices()
        .filter(|(index, character)| *index > 0 && character.is_ascii_uppercase())
        .map(|(index, _)| index)
        .chain(std::iter::once(accessor.len()))
        .filter(|index| owner.ends_with(&accessor[..*index]))
        .max()
        .unwrap_or(0);
    let suffix = &accessor[overlap..];
    (!suffix.is_empty()).then_some(suffix)
}

fn patch_symbol(patch: &SemanticPatch) -> String {
    format!(
        "{:?}:{}:{}:{}",
        patch.target.source,
        patch.target.operation_key,
        patch.target.schema_fqn,
        patch.target.field_path
    )
}

fn validate_imports(files: &BTreeMap<String, String>, config: &ProjectConfig) -> Result<()> {
    for (path, source) in files {
        for line in source
            .lines()
            .filter(|line| line.starts_with("import type "))
        {
            let Some((_, specifier)) = line.rsplit_once(" from ") else {
                bail!("invalid generated import in {path}: {line}");
            };
            let specifier = serde_json::from_str::<String>(specifier.trim_end_matches(';'))
                .map_err(|error| anyhow::anyhow!("invalid generated import in {path}: {error}"))?;
            let target = resolve_generated_module(path, &specifier, config)?;
            if !files.contains_key(&target) {
                bail!("generated import target missing: {path} -> {specifier} ({target})");
            }
        }
    }
    Ok(())
}

fn resolve_generated_module(
    from_file: &str,
    specifier: &str,
    config: &ProjectConfig,
) -> Result<String> {
    if let Some(relative) = specifier.strip_prefix("@/") {
        if !config.frontend.aliases.enabled {
            return Ok(format!(
                "{}.ts",
                join_path(&config.frontend.source_root, relative)
            ));
        }
    }
    for (alias, root) in [
        (
            &config.frontend.aliases.implementation,
            &config.frontend.layout.implementation_dir,
        ),
        (
            &config.frontend.aliases.types,
            &config.frontend.layout.types_dir,
        ),
        (
            &config.frontend.aliases.enums,
            &config.frontend.layout.enums_dir,
        ),
    ] {
        if let Some(relative) = specifier.strip_prefix(&format!("{alias}/")) {
            return Ok(format!("{}.ts", join_path(root, relative)));
        }
    }
    if let Some(relative) = specifier.strip_prefix("@/") {
        return Ok(format!(
            "{}.ts",
            join_path(&config.frontend.source_root, relative)
        ));
    }
    resolve_relative_module(from_file, specifier)
}

fn resolve_relative_module(from_file: &str, specifier: &str) -> Result<String> {
    if !specifier.starts_with('.') {
        bail!("generated import must be relative: {specifier}");
    }
    let mut components = normal_components(
        Path::new(from_file)
            .parent()
            .unwrap_or_else(|| Path::new("")),
    );
    for component in Path::new(specifier).components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                if components.pop().is_none() {
                    bail!("generated import escapes output root: {from_file} -> {specifier}");
                }
            }
            Component::Normal(value) => components.push(value.to_string_lossy().into_owned()),
            _ => bail!("invalid generated import: {specifier}"),
        }
    }
    Ok(format!("{}.ts", components.join("/")))
}

struct InterfaceRender<'a> {
    optional_fields: bool,
    base_targets: &'a HashMap<String, TypeTarget>,
    aliases: &'a HashMap<String, TypeTarget>,
    operation: Option<&'a Operation>,
    source: FieldSource,
    enum_targets: &'a HashMap<String, TypeTarget>,
    config: &'a ProjectConfig,
}

fn render_interface(
    schema: &Schema,
    target: &TypeTarget,
    render: InterfaceRender<'_>,
) -> Result<String> {
    let InterfaceRender {
        optional_fields,
        base_targets,
        aliases,
        operation,
        source,
        enum_targets,
        config,
    } = render;
    let mut imports = BTreeMap::<String, BTreeSet<String>>::new();
    let patches = operation
        .map(|operation| {
            operation
                .semantic_patches
                .iter()
                .filter(|patch| {
                    patch.target.schema_fqn == schema.fqn && patch.target.source == source
                })
                .map(|patch| (patch.target.field_name.as_str(), patch))
                .collect::<HashMap<_, _>>()
        })
        .unwrap_or_default();
    let mut fields = String::new();
    for field in &schema.fields {
        let patch = patches.get(field.name.as_str());
        let mut type_name =
            if let Some(patch) = patch.filter(|patch| patch.associated_values().is_some()) {
                let enum_target = enum_targets
                    .get(&patch_symbol(patch))
                    .with_context(|| format!("enum target missing for {}", patch_symbol(patch)))?;
                imports
                    .entry(import_specifier(&target.path, &enum_target.path, config))
                    .or_default()
                    .insert(enum_target.name.clone());
                enum_target.name.clone()
            } else {
                type_expression(
                    &field.java_type,
                    target,
                    base_targets,
                    aliases,
                    &mut imports,
                    config,
                )
            };
        if patch.is_some_and(|patch| patch.has_enum_null_branch()) {
            type_name.push_str(" | null");
        }
        if let Some(description) = &field.description {
            fields.push_str(&render_doc(description, "  "));
        }
        fields.push_str(&format!(
            "  {}{}: {};\n",
            safe_property(&field.name),
            if optional_fields || field.optional {
                "?"
            } else {
                ""
            },
            type_name
        ));
    }
    let mut output = String::from(GENERATED_HEADER);
    output.push_str(&render_imports(imports));
    if !output.ends_with("\n\n") {
        output.push('\n');
    }
    if let Some(description) = &schema.description {
        output.push_str(&render_doc(description, ""));
    }
    let type_parameters = if target.type_parameters.is_empty() {
        String::new()
    } else {
        format!("<{}>", target.type_parameters.join(", "))
    };
    output.push_str(&format!(
        "export interface {}{} {{\n{fields}}}\n",
        target.name, type_parameters
    ));
    Ok(output)
}

fn render_api_file(
    path: &str,
    operations: &[&Operation],
    base_targets: &HashMap<String, TypeTarget>,
    operation_aliases: &HashMap<String, HashMap<String, TypeTarget>>,
    config: &ProjectConfig,
) -> Result<String> {
    let mut imports = BTreeMap::<String, BTreeSet<String>>::new();
    let current = TypeTarget {
        name: String::new(),
        path: path.to_owned(),
        type_parameters: Vec::new(),
    };
    let mut method_names = BTreeSet::new();
    let mut urls = String::new();
    let mut bodies = String::new();
    for operation in operations {
        let export_name = lower_camel(&operation.method_name);
        if !method_names.insert(export_name.clone()) {
            bail!("generated method collision in {path}: {export_name}");
        }
        let empty_aliases = HashMap::new();
        let response = type_expression(
            &operation.response,
            &current,
            base_targets,
            operation_aliases
                .get(&operation.key)
                .unwrap_or(&empty_aliases),
            &mut imports,
            config,
        );
        urls.push_str(&format!(
            "  {}: {},\n",
            safe_property(&export_name),
            ts_string(&operation.route.path)
        ));
        let request_aliases = operation_aliases
            .get(&FieldSource::Request.operation_key(operation))
            .unwrap_or(&empty_aliases);
        let request = if operation.request_arguments.is_empty() {
            operation.request.as_ref().map(|request| {
                let type_name = type_expression(
                    request,
                    &current,
                    base_targets,
                    request_aliases,
                    &mut imports,
                    config,
                );
                (lower_camel(request.simple_name()), type_name)
            })
        } else if let [argument] = operation.request_arguments.as_slice()
            && argument.name.is_none()
        {
            let type_name = type_expression(
                &argument.java_type,
                &current,
                base_targets,
                request_aliases,
                &mut imports,
                config,
            );
            Some((lower_camel(argument.java_type.simple_name()), type_name))
        } else {
            let fields = operation
                .request_arguments
                .iter()
                .map(|argument| {
                    let name = argument.name.as_deref().expect("named request argument");
                    let kind = type_expression(
                        &argument.java_type,
                        &current,
                        base_targets,
                        request_aliases,
                        &mut imports,
                        config,
                    );
                    format!("{}?: {kind}", safe_property(name))
                })
                .collect::<Vec<_>>()
                .join("; ");
            Some(("request".to_owned(), format!("{{ {fields} }}")))
        };
        if let Some(description) = &operation.description {
            bodies.push_str(&render_doc(description, ""));
        }
        let parameters = request.as_ref().map_or_else(
            || {
                format!(
                    "options?: SecondParameter<typeof {}<{}>>",
                    config.frontend.request.export, response
                )
            },
            |(parameter, type_name)| {
                format!(
                    "{parameter}?: {type_name},\n  options?: SecondParameter<typeof {}<{}>>",
                    config.frontend.request.export, response
                )
            },
        );
        let payload = if operation.request_arguments.is_empty() {
            request.as_ref().map_or_else(String::new, |(parameter, _)| {
                if operation.route.method.eq_ignore_ascii_case("GET") {
                    format!("\n      params: {parameter},")
                } else {
                    format!("\n      headers: {{ 'Content-Type': 'application/json' }},\n      data: {parameter},")
                }
            })
        } else {
            let arguments = &operation.request_arguments;
            let direct = arguments.len() == 1 && arguments[0].name.is_none();
            let parameter = &request.as_ref().expect("request argument").0;
            let mut payload = String::new();
            for (location, property) in [
                (InputLocation::Query, "params"),
                (InputLocation::Body, "data"),
            ] {
                let selected = arguments
                    .iter()
                    .filter(|argument| argument.location == location)
                    .collect::<Vec<_>>();
                if selected.is_empty() {
                    continue;
                }
                if location == InputLocation::Body {
                    payload.push_str("\n      headers: { 'Content-Type': 'application/json' },");
                }
                let value = if direct || selected.len() == arguments.len() {
                    parameter.clone()
                } else {
                    let fields = selected
                        .iter()
                        .map(|argument| {
                            let name = argument.name.as_deref().expect("named request argument");
                            format!(
                                "{}: {parameter}?.[{}]",
                                safe_property(name),
                                ts_string(name)
                            )
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{{ {fields} }}")
                };
                payload.push_str(&format!("\n      {property}: {value},"));
            }
            payload
        };
        bodies.push_str(&format!(
            "export function {export_name}(\n  {parameters},\n): Promise<{}> {{\n  return {}<{}>(\n    {{\n      url: API_URLS.{export_name},\n      method: {},{payload}\n    }},\n    options,\n  );\n}}\n\n",
            response,
            config.frontend.request.export,
            response,
            ts_string(&operation.route.method.to_ascii_uppercase()),
        ));
    }
    Ok(format!(
        "{GENERATED_HEADER}{}import {{ {} }} from {};\n\ntype SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];\n\nconst API_URLS = {{\n{urls}}} as const;\n\n{bodies}",
        render_imports(imports),
        config.frontend.request.export,
        ts_string(&config.frontend.request.module),
    ))
}

fn type_expression(
    type_ref: &TypeRef,
    current: &TypeTarget,
    base_targets: &HashMap<String, TypeTarget>,
    aliases: &HashMap<String, TypeTarget>,
    imports: &mut BTreeMap<String, BTreeSet<String>>,
    config: &ProjectConfig,
) -> String {
    let scalar = if type_ref.arguments.is_empty()
        && current
            .type_parameters
            .iter()
            .any(|parameter| parameter == type_ref.simple_name())
    {
        Some(type_ref.simple_name())
    } else {
        match type_ref.simple_name() {
            "String" | "CharSequence" | "char" | "Character" | "Long" | "long" | "BigInteger"
            | "Date" | "LocalDate" | "LocalDateTime" | "Instant" | "Timestamp" => Some("string"),
            "Integer" | "int" | "Short" | "short" | "Byte" | "byte" | "Double" | "double"
            | "Float" | "float" | "BigDecimal" => Some("number"),
            "Boolean" | "boolean" => Some("boolean"),
            "Void" | "void" => Some("void"),
            "Object" | "JSONObject" => Some("unknown"),
            _ => None,
        }
    };
    let mut result = if let Some(scalar) = scalar {
        scalar.to_owned()
    } else if is_collection(type_ref.simple_name()) {
        format!(
            "{}[]",
            type_ref
                .arguments
                .first()
                .map(|item| type_expression(item, current, base_targets, aliases, imports, config))
                .unwrap_or_else(|| "unknown".to_owned())
        )
    } else if matches!(type_ref.simple_name(), "PageList" | "Page" | "PageResult") {
        let item = type_ref
            .arguments
            .last()
            .map(|item| type_expression(item, current, base_targets, aliases, imports, config))
            .unwrap_or_else(|| "unknown".to_owned());
        format!("{{ totalNum: number; list: {item}[] }}")
    } else if matches!(
        type_ref.simple_name(),
        "Map" | "HashMap" | "LinkedHashMap" | "TreeMap"
    ) {
        let value = type_ref
            .arguments
            .last()
            .map(|value| type_expression(value, current, base_targets, aliases, imports, config))
            .unwrap_or_else(|| "unknown".to_owned());
        format!("Record<string, {value}>")
    } else if type_ref.simple_name() == "Optional" {
        let value = type_ref
            .arguments
            .first()
            .map(|value| type_expression(value, current, base_targets, aliases, imports, config))
            .unwrap_or_else(|| "unknown".to_owned());
        format!("{value} | undefined")
    } else {
        let fqn = type_ref.name.replace("::", ".");
        let target = aliases.get(&fqn).or_else(|| base_targets.get(&fqn));
        if let Some(target) = target {
            if target.path != current.path {
                imports
                    .entry(import_specifier(&current.path, &target.path, config))
                    .or_default()
                    .insert(target.name.clone());
            }
            let arguments = if type_ref.arguments.is_empty() {
                vec!["unknown".to_owned(); target.type_parameters.len()]
            } else {
                type_ref
                    .arguments
                    .iter()
                    .map(|argument| {
                        type_expression(argument, current, base_targets, aliases, imports, config)
                    })
                    .collect()
            };
            if arguments.is_empty() {
                target.name.clone()
            } else {
                format!("{}<{}>", target.name, arguments.join(", "))
            }
        } else {
            "unknown".to_owned()
        }
    };
    for _ in 0..type_ref.array_depth {
        result = format!("{result}[]");
    }
    result
}

fn render_enum(name: &str, values: &[CodedValue], identity: &str, erasable: bool) -> String {
    let (origin, reference) = match identity.strip_prefix("comment:") {
        Some(field) => ("字段注释/注解", field),
        None => ("Java 枚举类", identity),
    };
    let description = render_doc(&format!("来源：{origin}\n引用：{reference}"), "");
    let separator = if erasable { ":" } else { " =" };
    let entries = values
        .iter()
        .map(|value| {
            let key = value.key.clone().unwrap_or_else(|| enum_key(&value.value));
            format!(
                "  /** {} */\n  {}{separator} {},\n",
                value.label.replace("*/", "* /"),
                sanitize_identifier(&key),
                wire_literal(&value.value)
            )
        })
        .collect::<String>();
    if !erasable {
        return format!("{GENERATED_HEADER}\n{description}export enum {name} {{\n{entries}}}\n");
    }
    format!(
        "{GENERATED_HEADER}\n{description}export const {name} = {{\n{entries}}} as const;\n\nexport type {name} = typeof {name}[keyof typeof {name}];\n"
    )
}

fn render_imports(imports: BTreeMap<String, BTreeSet<String>>) -> String {
    imports
        .into_iter()
        .map(|(path, names)| {
            format!(
                "import type {{ {} }} from {};\n",
                names.into_iter().collect::<Vec<_>>().join(", "),
                ts_string(&path)
            )
        })
        .collect()
}

fn render_doc(value: &str, indent: &str) -> String {
    let lines = value
        .replace("*/", "* /")
        .lines()
        .map(|line| format!("{indent} * {line}\n"))
        .collect::<String>();
    format!("{indent}/**\n{lines}{indent} */\n")
}

fn insert_file(files: &mut BTreeMap<String, String>, path: &str, source: String) -> Result<()> {
    if let Some(existing) = files.insert(path.to_owned(), source.clone()) {
        if existing != source {
            bail!("generated file collision: {path}");
        }
    }
    Ok(())
}

fn relative_import(from_file: &str, to_file: &str) -> String {
    let from = Path::new(from_file)
        .parent()
        .unwrap_or_else(|| Path::new(""));
    let to = Path::new(to_file).with_extension("");
    let from_parts = normal_components(from);
    let to_parts = normal_components(&to);
    let common = from_parts
        .iter()
        .zip(&to_parts)
        .take_while(|(left, right)| left == right)
        .count();
    let mut parts = vec![".."; from_parts.len() - common];
    parts.extend(to_parts[common..].iter().map(String::as_str));
    let value = parts.join("/");
    if value.starts_with('.') {
        value
    } else {
        format!("./{value}")
    }
}

fn import_specifier(from_file: &str, to_file: &str, config: &ProjectConfig) -> String {
    if !config.frontend.aliases.enabled {
        let relative = Path::new(to_file)
            .strip_prefix(&config.frontend.source_root)
            .expect("validated generated directories are inside sourceRoot");
        return format!(
            "@/{}",
            normal_components(&relative.with_extension("")).join("/")
        );
    }
    for (root, alias) in [
        (
            &config.frontend.layout.types_dir,
            &config.frontend.aliases.types,
        ),
        (
            &config.frontend.layout.enums_dir,
            &config.frontend.aliases.enums,
        ),
        (
            &config.frontend.layout.implementation_dir,
            &config.frontend.aliases.implementation,
        ),
    ] {
        if let Some(relative) = to_file.strip_prefix(&format!("{root}/")) {
            return format!(
                "{alias}/{}",
                relative.strip_suffix(".ts").unwrap_or(relative)
            );
        }
    }
    relative_import(from_file, to_file)
}

fn normal_components(path: &Path) -> Vec<String> {
    path.components()
        .filter_map(|component| match component {
            Component::Normal(value) => Some(value.to_string_lossy().into_owned()),
            _ => None,
        })
        .collect()
}

fn safe_property(value: &str) -> String {
    if is_identifier(value) {
        value.to_owned()
    } else {
        ts_string(value)
    }
}

fn is_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars.next().is_some_and(|character| {
        character == '_' || character == '$' || character.is_ascii_alphabetic()
    }) && chars
        .all(|character| character == '_' || character == '$' || character.is_ascii_alphanumeric())
}

fn enum_key(value: &WireValue) -> String {
    match value {
        WireValue::String(value) => value
            .to_ascii_uppercase()
            .replace(|character: char| !character.is_ascii_alphanumeric(), "_"),
        WireValue::Number(value) => format!("VALUE_{value}"),
        WireValue::Decimal(value) => format!("VALUE_{}", value.to_string().replace('.', "_")),
    }
}

fn wire_literal(value: &WireValue) -> String {
    match value {
        WireValue::String(value) => ts_string(value),
        WireValue::Number(value) => value.to_string(),
        WireValue::Decimal(value) => value.to_string(),
    }
}

fn ts_string(value: &str) -> String {
    serde_json::to_string(value).expect("serialize TypeScript string")
}

fn is_collection(name: &str) -> bool {
    matches!(
        name,
        "List" | "Set" | "Collection" | "ArrayList" | "LinkedList" | "HashSet" | "Iterable"
    )
}

#[cfg(test)]
pub(crate) mod tests {
    use super::super::model::ProvenanceStatus;
    use super::*;

    pub(crate) fn config() -> ProjectConfig {
        serde_json::from_value(serde_json::json!({
            "version": 1,
            "backend": {
                "repoPath": "/backend",
                "branch": "feature",
                "appName": "app",
                "contractRoot": "contract/src/main/java/p/contract"
            },
            "frontend": {
                "sourceRoot": "src",
                "buildTool": {
                    "kind": "vite",
                    "configPath": "vite.config.ts",
                    "testConfigs": []
                },
                "tsconfigPath": "tsconfig.json",
                "request": {
                    "module": "@/utils/request",
                    "export": "nlabRequest",
                    "responseMode": "unwrapped"
                },
                "response": {
                    "successCode": "0",
                    "codeFields": ["code", "respCode"],
                    "dataFields": ["data", "respData"]
                },
                "layout": {
                    "preset": "service",
                    "implementationDir": "src/service",
                    "typesDir": "src/types/service-type",
                    "enumsDir": "src/types/service-enums"
                },
                "aliases": {
                    "implementation": "@service",
                    "types": "@service-types",
                    "enums": "@service-enums"
                }
            }
        }))
        .unwrap()
    }

    #[test]
    fn gateway_mapped_arguments_generate_named_query_requests() {
        use serde_json::{Value, json};

        let kind = |name: &str| json!({"name": name, "arguments": [], "arrayDepth": 0});
        let operation = |method: &str, path: &str, request: Value, arguments: Value| {
            json!({
                "key": format!("IAdminCommonFacade#{method}"),
                "facadeName": "IAdminCommonFacade",
                "facadeFqn": "p.contract.IAdminCommonFacade",
                "methodName": method,
                "signature": "String ()",
                "description": null,
                "contractSource": "contract/src/main/java/p/contract/IAdminCommonFacade.java",
                "request": request,
                "requestArguments": arguments,
                "response": kind("String"),
                "requestSchema": null,
                "responseSchema": null,
                "service": null,
                "route": {"status": "resolved", "source": "zgateway", "method": "GET", "path": path, "host": null},
                "semanticPatches": [],
                "warnings": []
            })
        };
        let argument = |index: usize, java_name: &str, name: &str, ty: &str| {
            json!({
                "index": index, "javaName": java_name, "name": name,
                "javaType": kind(ty), "location": "query"
            })
        };
        let ir: ContractIr = serde_json::from_value(json!({
            "target": {"appName": "app", "branch": "feature", "commit": "abc", "codegraphVersion": "1", "codegraphExtractionVersion": "1"},
            "operations": [
                operation("brandModelSearch", "/api/brandModelSearch", Value::Null, json!([
                    argument(0, "cateId", "cateId", "Integer"),
                    argument(1, "brandId", "brandId", "Integer"),
                    argument(2, "cateType", "cateType", "Integer")
                ])),
                operation("getCommonEnum", "/api/commenums", kind("String"), json!([
                    argument(0, "type", "code", "String")
                ]))
            ],
            "schemas": {}
        })).unwrap();

        let generated = generate(&ir, &config()).unwrap();
        let api = generated
            .files
            .values()
            .find(|source| source.contains("export function brandModelSearch("))
            .unwrap();
        assert!(api.contains("request?: { cateId?: number; brandId?: number; cateType?: number }"));
        assert!(api.contains("export function getCommonEnum(\n  request?: { code?: string }"));
        assert!(api.contains("params: request,"));
        let openapi = super::super::openapi::generate(&ir, &config()).unwrap();
        let document: Value = serde_json::from_str(&openapi.source).unwrap();
        let search = &document["paths"]["/api/brandModelSearch"]["get"];
        assert_eq!(
            search["parameters"]
                .as_array()
                .unwrap()
                .iter()
                .map(|parameter| parameter["name"].as_str().unwrap())
                .collect::<Vec<_>>(),
            ["cateId", "brandId", "cateType"]
        );
        assert_eq!(search["parameters"][0]["schema"]["type"], "number");
        assert!(search.get("requestBody").is_none());
        assert_eq!(
            document["paths"]["/api/commenums"]["get"]["parameters"][0]["name"],
            "code"
        );
    }

    #[test]
    fn multiple_body_arguments_keep_nested_request_types() {
        use serde_json::{Value, json};

        let kind = |name: &str| json!({"name": name, "arguments": [], "arrayDepth": 0});
        let ir: ContractIr = serde_json::from_value(json!({
            "target": {"appName": "app", "branch": "feature", "commit": "abc", "codegraphVersion": "1", "codegraphExtractionVersion": "1"},
            "operations": [{
                "key": "IFacade#submit", "facadeName": "IFacade", "facadeFqn": "p.contract.IFacade",
                "methodName": "submit", "signature": "String (Payload payload, Integer mode)",
                "description": null,
                "contractSource": "contract/src/main/java/p/contract/IFacade.java",
                "request": null,
                "requestArguments": [
                    {"index": 0, "javaName": "payload", "name": "payload", "javaType": kind("p.Payload"), "location": "body"},
                    {"index": 1, "javaName": "mode", "name": "mode", "javaType": kind("Integer"), "location": "body"}
                ],
                "response": kind("String"), "requestSchema": null, "responseSchema": null,
                "service": null,
                "route": {"status": "resolved", "source": "zgateway", "method": "POST", "path": "/submit", "host": null},
                "semanticPatches": [], "warnings": []
            }],
            "schemas": {"p.Payload": {
                "fqn": "p.Payload", "name": "Payload", "sourcePath": "Payload.java", "description": null,
                "fields": [{"name": "value", "javaType": kind("String"), "optional": false, "description": null, "declaredValues": null}]
            }}
        })).unwrap();

        let generated = generate(&ir, &config()).unwrap();
        let api = generated
            .files
            .values()
            .find(|source| source.contains("export function submit("))
            .unwrap();
        assert!(api.contains("request?: { payload?: Payload; mode?: number }"));
        assert!(api.contains("data: request,"));
        assert!(
            generated
                .files
                .values()
                .any(|source| source.contains("export interface Payload {\n  value?: string;"))
        );
        let openapi = super::super::openapi::generate(&ir, &config()).unwrap();
        let document: Value = serde_json::from_str(&openapi.source).unwrap();
        let request = &document["paths"]["/submit"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"];
        assert_eq!(
            request["properties"]["payload"]["$ref"],
            "#/components/schemas/Payload"
        );
        assert_eq!(request["properties"]["mode"]["type"], "number");
    }

    #[test]
    fn relative_imports_are_lexical_and_extensionless() {
        assert_eq!(
            relative_import("api/recycle/query.ts", "types/share/order.ts"),
            "../../types/share/order"
        );
        assert_eq!(
            relative_import("types/recycle/query.ts", "types/recycle/order.ts"),
            "./order"
        );
    }

    #[test]
    fn word_conversion_keeps_initialisms_stable_enough() {
        assert_eq!(
            upper_camel("queryRecycleOrderList"),
            "QueryRecycleOrderList"
        );
        assert_eq!(lower_camel("IRecycleQueryFacade"), "iRecycleQueryFacade");
        assert_eq!(
            remove_owner_overlap("RecycleDetailAction", "ActionCode"),
            Some("Code")
        );
        assert_eq!(
            remove_owner_overlap("RefurbButton", "ActionCode"),
            Some("ActionCode")
        );
    }

    #[test]
    fn equivalent_types_are_reused_and_nested_enum_domains_stay_distinct() {
        use serde_json::json;

        let type_ref = |name: &str| json!({"name": name, "arguments": [], "arrayDepth": 0});
        let field = |name: &str, java_type: serde_json::Value| json!({"name": name, "javaType": java_type, "optional": false});
        let schema = |name: &str, fields: serde_json::Value| json!({"name": name, "fqn": format!("p.{name}"), "sourcePath": format!("{name}.java"), "fields": fields});
        let operation = |method: &str, domain: Option<&str>| {
            let key = format!("IFacade#{method}");
            json!({
                "key": key, "facadeName": "IFacade", "facadeFqn": "p.contract.IFacade",
                "methodName": method, "signature": format!("Detail {method}()"),
                "contractSource": "contract/src/main/java/p/contract/IFacade.java",
                "response": type_ref("p.Detail"),
                "route": {"status": "placeholder", "source": "placeholder", "method": "POST", "path": format!("/{method}")},
                "semanticPatches": domain.map(|domain| vec![json!({
                    "target": {"operationKey": key, "schemaFqn": "p.BizButton", "fieldPath": "buttons.items[].actionCode", "fieldName": "actionCode"},
                    "status": "closed", "enumFqn": domain, "enumSource": format!("{method}/{domain}.java"), "accessor": "getActionCode",
                    "values": [{"value": "start", "key": "START", "label": "开始"}],
                    "primaryEnumValue": true, "evidence": [method]
                })]).unwrap_or_default(),
                "warnings": []
            })
        };
        let mut ir: ContractIr = serde_json::from_value(json!({
            "target": {"appName": "app", "branch": "feature", "commit": "abc", "codegraphVersion": "1", "codegraphExtractionVersion": "1"},
            "operations": [operation("queryRecycle", Some("p.RecycleActionEnum"))],
            "schemas": {
                "p.Detail": schema("Detail", json!([
                    field("buttons", json!({"name": "p.Envelope", "arguments": [type_ref("p.BizButton")], "arrayDepth": 0})),
                    field("auditInfo", type_ref("p.OperationAuditInfo")),
                    field("children", json!({"name": "p.Detail", "arguments": [], "arrayDepth": 1}))
                ])),
                "p.Envelope": {"name": "Envelope", "fqn": "p.Envelope", "sourcePath": "Envelope.java", "typeParameters": ["T"],
                    "fields": [field("items", json!({"name": "T", "arguments": [], "arrayDepth": 1}))]},
                "p.BizButton": schema("BizButton", json!([field("actionCode", type_ref("String"))])),
                "p.OperationAuditInfo": schema("OperationAuditInfo", json!([field("name", type_ref("String"))])),
                "p.Unused": schema("Unused", json!([]))
            }
        })).unwrap();
        let config = config();
        let single = generate(&ir, &config).unwrap();
        assert_eq!(single.type_files.len(), 4);
        let button = &single.files["src/types/service-type/facade/bizButton.ts"];
        assert!(button.contains("export interface BizButton {"));
        assert!(button.contains("actionCode: RecycleActionCode;"));
        assert!(
            !single
                .files
                .values()
                .any(|source| source.contains("Unused"))
        );

        for (method, domain) in [
            ("queryRecycleAgain", Some("p.RecycleActionEnum")),
            ("queryWorkOrder", Some("p.WorkOrderActionEnum")),
            ("queryRaw", None),
        ] {
            ir.operations
                .push(serde_json::from_value(operation(method, domain)).unwrap());
        }
        let generated = generate(&ir, &config).unwrap();
        let plan = schema_plan(&ir);
        let recycle = &plan.aliases["IFacade#queryRecycle"];
        assert_eq!(recycle, &plan.aliases["IFacade#queryRecycleAgain"]);
        let work_order = &plan.aliases["IFacade#queryWorkOrder"];
        let raw = &plan.aliases["IFacade#queryRaw"];
        assert_ne!(recycle["p.BizButton"], work_order["p.BizButton"]);
        assert_ne!(recycle["p.Detail"], work_order["p.Detail"]);
        assert_eq!(raw["p.BizButton"], "BizButton");
        assert_eq!(raw["p.Detail"], "Detail");
        assert_eq!(generated.type_files.len(), 8);
        for aliases in [recycle, work_order, raw] {
            let detail = generated
                .files
                .values()
                .find(|source| {
                    source.contains(&format!("export interface {} {{", aliases["p.Detail"]))
                })
                .unwrap();
            assert!(detail.contains(&format!("buttons: Envelope<{}>;", aliases["p.BizButton"])));
            assert!(detail.contains(&format!("children: {}[];", aliases["p.Detail"])));
            assert!(detail.contains("auditInfo: OperationAuditInfo;"));
        }
        let openapi = super::super::openapi::generate(&ir, &config).unwrap();
        assert_eq!(openapi.schemas, generated.type_files.len());
        let document: serde_json::Value = serde_json::from_str(&openapi.source).unwrap();
        for method in [
            "queryRecycle",
            "queryRecycleAgain",
            "queryWorkOrder",
            "queryRaw",
        ] {
            let name = &plan.aliases[&format!("IFacade#{method}")]["p.Detail"];
            assert_eq!(
                document["paths"][format!("/{method}")]["post"]["responses"]["200"]["content"]["application/json"]
                    ["schema"]["$ref"],
                format!("#/components/schemas/{name}")
            );
        }
        ir.operations.reverse();
        assert_eq!(generate(&ir, &config).unwrap().files, generated.files);
        let reordered = super::super::openapi::generate(&ir, &config).unwrap();
        assert_eq!(
            serde_json::from_str::<serde_json::Value>(&reordered.source).unwrap(),
            document
        );
        ir.operations
            .retain(|operation| operation.method_name != "queryRaw");
        let shared = generate(&ir, &config).unwrap();
        assert_eq!(shared.type_files.len(), 8);
        assert!(
            shared.files["src/types/service-type/facade/bizButton.ts"]
                .contains("actionCode: string;")
        );
    }

    #[test]
    fn generic_schema_preserves_concrete_type_in_typescript_and_openapi() {
        let ir = serde_json::from_value::<ContractIr>(serde_json::json!({
            "target": {
                "appName": "app",
                "branch": "feature",
                "commit": "abc",
                "codegraphVersion": "1",
                "codegraphExtractionVersion": "1"
            },
            "operations": [{
                "key": "IWorkOrderQueryFacade#queryWorkOrderList",
                "facadeName": "IWorkOrderQueryFacade",
                "facadeFqn": "p.contract.warehouse.IWorkOrderQueryFacade",
                "methodName": "queryWorkOrderList",
                "signature": "PageResp<WorkOrderListItemVO> queryWorkOrderList()",
                "description": null,
                "contractSource": "contract/src/main/java/p/contract/warehouse/IWorkOrderQueryFacade.java",
                "request": null,
                "response": {
                    "name": "p.PageResp",
                    "arguments": [{
                        "name": "p.WorkOrderListItemVO",
                        "arguments": [],
                        "arrayDepth": 0
                    }],
                    "arrayDepth": 0
                },
                "requestSchema": null,
                "responseSchema": "p.PageResp",
                "service": null,
                "route": {
                    "status": "placeholder",
                    "source": "placeholder",
                    "method": "POST",
                    "path": "/query",
                    "host": null
                },
                "semanticPatches": [],
                "warnings": []
            }],
            "schemas": {
                "p.PageResp": {
                    "fqn": "p.PageResp",
                    "name": "PageResp",
                    "sourcePath": "PageResp.java",
                    "description": null,
                    "typeParameters": ["T"],
                    "fields": [{
                        "name": "list",
                        "javaType": {
                            "name": "List",
                            "arguments": [{
                                "name": "T",
                                "arguments": [],
                                "arrayDepth": 0
                            }],
                            "arrayDepth": 0
                        },
                        "optional": false,
                        "description": null,
                        "declaredValues": null
                    }]
                },
                "p.WorkOrderListItemVO": {
                    "fqn": "p.WorkOrderListItemVO",
                    "name": "WorkOrderListItemVO",
                    "sourcePath": "WorkOrderListItemVO.java",
                    "description": null,
                    "fields": [{
                        "name": "workOrderNo",
                        "javaType": {
                            "name": "Long",
                            "arguments": [],
                            "arrayDepth": 0
                        },
                        "optional": false,
                        "description": null,
                        "declaredValues": null
                    }]
                }
            }
        }))
        .unwrap();

        let artifact = generate(&ir, &config()).unwrap();
        let page = artifact
            .files
            .values()
            .find(|source| source.contains("export interface PageResp"))
            .unwrap();
        assert!(page.contains("export interface PageResp<T>"));
        assert!(page.contains("list: T[];"));
        let data = artifact
            .files
            .values()
            .find(|source| source.contains("PageResp<WorkOrderListItemVO>"))
            .unwrap();
        assert!(data.contains("import type { PageResp }"));
        assert!(data.contains("import type { WorkOrderListItemVO }"));
        assert!(data.contains("Promise<PageResp<WorkOrderListItemVO>>"));
        assert_eq!(artifact.type_files.len(), 2);

        let openapi = super::super::openapi::generate(&ir, &config()).unwrap();
        let document = serde_json::from_str::<serde_json::Value>(&openapi.source).unwrap();
        let response = &document["paths"]["/query"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"];
        assert_eq!(response["type"], "object");
        assert_eq!(
            response["properties"]["list"]["items"]["$ref"],
            "#/components/schemas/WorkOrderListItemVO"
        );
    }

    #[test]
    fn only_request_root_fields_are_optional() {
        use serde_json::{Value, json};

        let type_ref = |name: &str| json!({ "name": name, "arguments": [], "arrayDepth": 0 });
        let field = |name: &str, java_type: Value| {
            json!({
                "name": name, "javaType": java_type, "optional": false,
                "description": null, "declaredValues": null
            })
        };
        let envelope = json!({
            "name": "p.Envelope", "arguments": [type_ref("p.Item")], "arrayDepth": 0
        });
        let mut ir: ContractIr = serde_json::from_value(json!({
            "target": {
                "appName": "app", "branch": "feature", "commit": "abc",
                "codegraphVersion": "1", "codegraphExtractionVersion": "1"
            },
            "operations": [{
                "key": "IFacade#submit", "facadeName": "IFacade",
                "facadeFqn": "p.contract.IFacade", "methodName": "submit",
                "signature": "Envelope<Item> (SubmitReq req)", "description": null,
                "contractSource": "contract/src/main/java/p/contract/IFacade.java",
                "request": type_ref("p.SubmitReq"), "requestSchema": "p.SubmitReq",
                "response": envelope, "responseSchema": "p.Envelope", "service": null,
                "route": { "status": "placeholder", "source": "placeholder",
                    "method": "POST", "path": "/submit", "host": null },
                "semanticPatches": [], "warnings": []
            }],
            "schemas": {
                "p.SubmitReq": {
                    "fqn": "p.SubmitReq", "name": "SubmitReq",
                    "sourcePath": "SubmitReq.java", "description": null,
                    "fields": [field("operatorName", type_ref("String")), field("payload", envelope)]
                },
                "p.Envelope": {
                    "fqn": "p.Envelope", "name": "Envelope", "typeParameters": ["T"],
                    "sourcePath": "Envelope.java", "description": null,
                    "fields": [field("list", json!({
                        "name": "List", "arguments": [type_ref("T")], "arrayDepth": 0
                    }))]
                },
                "p.Item": {
                    "fqn": "p.Item", "name": "Item", "sourcePath": "Item.java", "description": null,
                    "fields": [field("id", type_ref("Long")), field("children", json!({
                        "name": "p.Item", "arguments": [], "arrayDepth": 1
                    }))]
                }
            }
        })).unwrap();
        let original = ir.clone();
        let artifact = generate(&ir, &config()).unwrap();
        let source = |declaration: &str| {
            artifact
                .files
                .values()
                .find(|source| source.contains(declaration))
                .unwrap()
        };
        assert!(source("export interface SubmitReq {").contains("operatorName?: string;"));
        assert!(source("export interface SubmitReq {").contains("payload?: Envelope<Item>;"));
        assert!(source("export interface Envelope<T>").contains("list: T[];"));
        assert!(source("export interface Item {").contains("id: string;"));
        assert!(source("export interface Item {").contains("children: Item[];"));
        assert_eq!(artifact.type_files.len(), 3);
        assert!(source("export function submit(").contains("submitReq?: SubmitReq,"));

        let openapi = super::super::openapi::generate(&ir, &config()).unwrap();
        let document: Value = serde_json::from_str(&openapi.source).unwrap();
        let schemas = &document["components"]["schemas"];
        assert!(schemas["SubmitReq"].get("required").is_none());
        assert_eq!(schemas["Envelope"]["required"], json!(["list"]));
        assert_eq!(schemas["Item"]["required"], json!(["id", "children"]));
        let operation = &document["paths"]["/submit"]["post"];
        assert_eq!(operation["requestBody"]["required"], false);
        let response = &operation["responses"]["200"]["content"]["application/json"]["schema"];
        assert_eq!(response["required"], json!(["list"]));
        let item_ref = response["properties"]["list"]["items"]["$ref"]
            .as_str()
            .unwrap();
        let item = document.pointer(&item_ref[1..]).unwrap();
        assert_eq!(item["required"], json!(["id", "children"]));
        assert_eq!(item["properties"]["children"]["items"]["$ref"], item_ref);
        assert_eq!(
            ir, original,
            "output policy must not mutate backend evidence"
        );

        // Generic request bodies are rendered inline by OpenAPI.
        ir.operations[0].request = Some(ir.operations[0].response.clone());
        let artifact = generate(&ir, &config()).unwrap();
        let plan = target_plan(&ir, &config()).unwrap();
        assert!(artifact.files[&plan.base["p.Envelope"].path].contains("list?: T[];"));
        assert!(artifact.files[&plan.base["p.Item"].path].contains("id: string;"));
        let aliases = &plan.aliases[&ir.operations[0].key];
        assert!(artifact.files[&aliases["p.Envelope"].path].contains("list: T[];"));
        assert!(artifact.files[&aliases["p.Item"].path].contains("id: string;"));
        let openapi = super::super::openapi::generate(&ir, &config()).unwrap();
        let document: Value = serde_json::from_str(&openapi.source).unwrap();
        let request = &document["paths"]["/submit"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"];
        assert!(request.get("required").is_none());
        assert_eq!(
            request["properties"]["list"]["items"]["$ref"],
            "#/components/schemas/Item"
        );
    }

    #[test]
    fn declared_values_remain_scalar_without_verified_primary() {
        let integer = TypeRef {
            name: "Integer".to_owned(),
            arguments: vec![],
            array_depth: 0,
        };
        let refurb_status_values = super::super::coded_values::parse(
            "status",
            Some("整备单状态：10-待整备 20-整备中 30-待拍照 80-整备完成 90-取消整备"),
            None,
            &integer,
        )
        .unwrap();
        let ir = serde_json::from_value::<ContractIr>(serde_json::json!({
            "target": {
                "appName": "app",
                "branch": "feature",
                "commit": "abc",
                "codegraphVersion": "1",
                "codegraphExtractionVersion": "1"
            },
            "operations": [{
                "key": "IGoodsQueryFacade#queryRefurbOrderList",
                "facadeName": "IGoodsQueryFacade",
                "facadeFqn": "p.contract.checkapp.IGoodsQueryFacade",
                "methodName": "queryRefurbOrderList",
                "signature": "RefurbOrderVO queryRefurbOrderList()",
                "description": null,
                "contractSource": "contract/src/main/java/p/contract/checkapp/IGoodsQueryFacade.java",
                "request": null,
                "response": { "name": "p.RefurbOrderVO", "arguments": [], "arrayDepth": 0 },
                "requestSchema": null,
                "responseSchema": "p.RefurbOrderVO",
                "service": null,
                "route": {
                    "status": "placeholder",
                    "source": "placeholder",
                    "method": "POST",
                    "path": "/query",
                    "host": null
                },
                "semanticPatches": [],
                "warnings": []
            }],
            "schemas": {
                "p.RefurbOrderVO": {
                    "fqn": "p.RefurbOrderVO",
                    "name": "RefurbOrderVO",
                    "sourcePath": "RefurbOrderVO.java",
                    "description": null,
                    "fields": [{
                        "name": "status",
                        "javaType": { "name": "Integer", "arguments": [], "arrayDepth": 0 },
                        "optional": false,
                        "description": "整备单状态",
                        "declaredValues": refurb_status_values
                    }]
                }
            }
        }))
        .unwrap();

        let config = config();
        let openapi = super::super::openapi::generate(&ir, &config).unwrap();
        let document = serde_json::from_str::<serde_json::Value>(&openapi.source).unwrap();
        let status_schema =
            &document["components"]["schemas"]["RefurbOrderVO"]["properties"]["status"];
        assert!(status_schema.get("enum").is_none());
        assert!(status_schema.get("x-enum-varnames").is_none());

        let artifact = generate(&ir, &config).unwrap();
        assert!(artifact.enum_files.is_empty());
        let type_source = artifact
            .files
            .values()
            .find(|source| source.contains("export interface RefurbOrderVO"))
            .expect("RefurbOrderVO type");
        assert!(type_source.contains("status: number;"));
    }

    #[test]
    fn generation_uses_facade_layout_request_adapter_and_separate_enum() {
        let ir = serde_json::from_value::<ContractIr>(serde_json::json!({
            "target": {
                "appName": "app",
                "branch": "feature",
                "commit": "abc",
                "codegraphVersion": "1",
                "codegraphExtractionVersion": "1"
            },
            "operations": [{
                "key": "IGoodsQueryFacade#queryButtons",
                "facadeName": "IGoodsQueryFacade",
                "facadeFqn": "p.contract.checkapp.IGoodsQueryFacade",
                "methodName": "queryButtons",
                "signature": "BizButton queryButtons()",
                "description": null,
                "contractSource": "contract/src/main/java/p/contract/checkapp/IGoodsQueryFacade.java",
                "request": null,
                "response": { "name": "p.BizButton", "arguments": [], "arrayDepth": 0 },
                "requestSchema": null,
                "responseSchema": "p.BizButton",
                "service": null,
                "route": {
                    "status": "placeholder",
                    "source": "placeholder",
                    "method": "POST",
                    "path": "/query",
                    "host": null
                },
                "semanticPatches": [{
                    "target": {
                        "operationKey": "IGoodsQueryFacade#queryButtons",
                        "schemaFqn": "p.BizButton",
                        "fieldPath": "actionCode",
                        "fieldName": "actionCode"
                    },
                    "status": "closed",
                    "enumFqn": "p.RefurbButtonEnum",
                    "enumSource": "RefurbButtonEnum.java",
                    "accessor": "getActionCode",
                    "values": [{
                        "value": "start_refurb",
                        "key": "START_REFURB",
                        "label": "去整备"
                    }],
                    "primaryEnumValue": true,
                    "evidence": ["test"],
                    "warning": null
                }],
                "warnings": []
            }],
            "schemas": {
                "p.BizButton": {
                    "fqn": "p.BizButton",
                    "name": "BizButton",
                    "sourcePath": "BizButton.java",
                    "description": null,
                    "fields": [{
                        "name": "actionCode",
                        "javaType": { "name": "String", "arguments": [], "arrayDepth": 0 },
                        "optional": false,
                        "description": null,
                        "declaredValues": null
                    }]
                }
            }
        }))
        .unwrap();

        let artifact = generate(&ir, &config()).unwrap();
        let api = &artifact.files["src/service/checkapp/goodsQueryFacade.ts"];
        assert_eq!(api.matches("const API_URLS =").count(), 1);
        assert!(api.contains("queryButtons: \"/query\""));
        assert!(api.contains("url: API_URLS.queryButtons"));
        assert!(!api.contains("getQueryButtonsUrl"));
        let mut no_aliases = config();
        no_aliases.frontend.aliases.enabled = false;
        let plain = generate(&ir, &no_aliases).unwrap();
        assert!(
            plain
                .files
                .values()
                .any(|source| source.contains("from \"@/types/service-enums/"))
        );
        assert!(
            plain
                .files
                .values()
                .any(|source| source.contains("from \"@/types/service-type/"))
        );
        assert!(
            plain
                .files
                .values()
                .all(|source| !source.contains("from \"@service"))
        );
        assert_eq!(
            resolve_generated_module("src/service/a.ts", "@/types/service-type/item", &no_aliases)
                .unwrap(),
            "src/types/service-type/item.ts"
        );
        assert!(api.contains("from \"@/utils/request\""));
        assert!(api.contains("return nlabRequest<"));
        assert!(!api.contains("fetch("));
        assert_eq!(artifact.enum_files.len(), 1);
        let enum_source = &artifact.files[&artifact.enum_files[0]];
        assert!(enum_source.contains("export const RefurbButtonActionCode ="));
        assert!(enum_source.contains("来源：Java 枚举类"));
        assert!(enum_source.contains("引用：p.RefurbButtonEnum#getActionCode"));
        assert!(enum_source.contains("START_REFURB: \"start_refurb\""));
        let mut serialized = serde_json::to_value(config()).unwrap();
        assert_eq!(serialized["EnumIrisable"], true);
        serialized["EnumIrisable"] = serde_json::json!(false);
        let native_config = serde_json::from_value(serialized).unwrap();
        let native = generate(&ir, &native_config).unwrap();
        assert_eq!(native.enum_files, artifact.enum_files);
        let native_source = &native.files[&native.enum_files[0]];
        assert!(native_source.contains("export enum RefurbButtonActionCode {"));
        assert!(native_source.contains("START_REFURB = \"start_refurb\","));
        assert!(native_source.contains("引用：p.RefurbButtonEnum#getActionCode"));
        assert!(!native_source.contains("export type"));
        let patched_type = artifact
            .files
            .values()
            .find(|source| source.contains("actionCode: RefurbButtonActionCode"))
            .expect("patched operation type");
        assert!(
            patched_type
                .contains("@service-enums/checkapp/goodsQueryFacade/refurbButtonActionCode")
        );

        let mut associated_ir = ir.clone();
        {
            let patch = &mut associated_ir.operations[0].semantic_patches[0];
            patch.status = ProvenanceStatus::Known;
            patch.values.clear();
            patch.known_values = vec![CodedValue {
                value: WireValue::String("start_refurb".to_owned()),
                key: Some("START_REFURB".to_owned()),
                label: "去整备".to_owned(),
            }];
            patch.enum_associated = true;
            patch.primary_enum_value = true;
            patch.nullable = true;
        }
        let associated = generate(&associated_ir, &config()).unwrap();
        let associated_type = associated
            .files
            .values()
            .find(|source| source.contains("actionCode: RefurbButtonActionCode"))
            .expect("associated operation type");
        assert!(associated_type.contains("actionCode: RefurbButtonActionCode | null;"));
        let associated_openapi =
            super::super::openapi::generate(&associated_ir, &config()).unwrap();
        let associated_document =
            serde_json::from_str::<serde_json::Value>(&associated_openapi.source).unwrap();
        let response_ref = associated_document["paths"]["/query"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"]
            .as_str()
            .unwrap();
        let property = associated_document
            .pointer(&format!("{}/properties/actionCode", &response_ref[1..]))
            .unwrap();
        assert_eq!(
            property["anyOf"][0]["enum"],
            serde_json::json!(["start_refurb"])
        );
        assert_eq!(property["anyOf"][1], serde_json::json!({"type": "null"}));
        assert_eq!(
            property["x-nlab-enum-association"]["enumAssociated"],
            serde_json::json!(true)
        );
        assert_eq!(
            associated_document["paths"]["/query"]["post"]["x-nlab-semantic-patches"][0]["enumAssociated"],
            serde_json::json!(true)
        );
        assert_eq!(
            associated_document["paths"]["/query"]["post"]["x-nlab-semantic-patches"][0]["nullable"],
            serde_json::json!(true)
        );

        associated_ir.operations[0].semantic_patches[0].enum_associated = false;
        associated_ir.operations[0].semantic_patches[0].nullable = true;
        let known_only = generate(&associated_ir, &config()).unwrap();
        assert!(
            known_only
                .files
                .values()
                .any(|source| source.contains("actionCode: string | null;"))
        );
    }
}
